-- ============================================================================
-- BAGAMA HVAC Management System - Full Database Schema Initialization
-- ============================================================================
-- Generated: 2026-05-26
-- Description: Consolidated idempotent schema migration combining all individual
--              migration files into a single comprehensive initialization script.
-- 
-- FEATURES:
--   - Fully idempotent (safe to run multiple times)
--   - Uses IF NOT EXISTS for all CREATE statements
--   - Uses DO $$ blocks for conditional ALTER TABLE statements
--   - Works on both plain PostgreSQL (pgAdmin) and Supabase
--   - Ordered by dependency (referenced tables first)
--   - Includes all constraints, foreign keys, defaults, indexes, triggers
--   - Includes RBAC seed data with default roles and permissions
--
-- MODULES:
--   1. Core Infrastructure (branches, settings)
--   2. RBAC & Authentication
--   3. Inventory (brands, products, capacity, materials, parts)
--   4. Vendors & Customers
--   5. Purchase Orders
--   6. Sales Orders
--   7. Serial Numbers
--   8. Quotations
--   9. Projects
--  10. Accounting (cheque vouchers, general journal, tax)
--  11. Payroll
--  12. Audit Logs
--  13. Triggers & Functions
--  14. Seed Data (RBAC permissions, roles, menus)
-- ============================================================================

BEGIN;

-- ============================================================================
-- MODULE 1: CORE INFRASTRUCTURE
-- ============================================================================

-- 1.1 Branches
CREATE TABLE IF NOT EXISTS public.tblbranches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "branchName" VARCHAR(255) NULL,
  "branchAddress" TEXT NULL
);

-- 1.2 Settings
CREATE TABLE IF NOT EXISTS public.tblsettings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "businessName" TEXT NULL,
  "businessAddress" TEXT NULL,
  "businessEmail" VARCHAR NULL,
  "businessContact" VARCHAR NULL,
  "businessTIN" VARCHAR NULL,
  "businessOwner" VARCHAR NULL,
  "businessLogo" TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Settings additional columns
DO $$ BEGIN
  ALTER TABLE public.tblsettings ADD COLUMN IF NOT EXISTS "businessLogoLight" TEXT;
  ALTER TABLE public.tblsettings ADD COLUMN IF NOT EXISTS "businessLogoDark" TEXT;
  ALTER TABLE public.tblsettings ADD COLUMN IF NOT EXISTS "drTemplatePdf" TEXT;
  ALTER TABLE public.tblsettings ADD COLUMN IF NOT EXISTS cv_number_prefix TEXT DEFAULT 'CV';
  ALTER TABLE public.tblsettings ADD COLUMN IF NOT EXISTS cv_number_suffix TEXT DEFAULT '';
  ALTER TABLE public.tblsettings ADD COLUMN IF NOT EXISTS gj_number_prefix TEXT DEFAULT 'GJ';
  ALTER TABLE public.tblsettings ADD COLUMN IF NOT EXISTS gj_number_suffix TEXT DEFAULT '';
  ALTER TABLE public.tblsettings ADD COLUMN IF NOT EXISTS website_tab_name TEXT;
  ALTER TABLE public.tblsettings ADD COLUMN IF NOT EXISTS routing_tab_name TEXT;
END $$;

-- ============================================================================
-- MODULE 2: RBAC & AUTHENTICATION
-- ============================================================================

-- 2.1 Roles table (legacy)
CREATE TABLE IF NOT EXISTS public.tblrbac (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "roleName" VARCHAR(50) NULL,
  "roleMenus" TEXT NULL,
  "rolePermission" TEXT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2.2 Users
CREATE TABLE IF NOT EXISTS public.tblusers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NULL,
  password TEXT NULL,
  fullname VARCHAR(100) NULL,
  birthdate DATE NULL,
  address TEXT NULL,
  email VARCHAR(100) NULL,
  contact VARCHAR(50) NULL,
  status SMALLINT NULL,
  is_deleted BOOLEAN NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NULL DEFAULT NOW(),
  created_by BIGINT NULL DEFAULT 1,
  "roleId" BIGINT NULL DEFAULT 1,
  "branchId" BIGINT NULL
);

-- Users foreign keys (conditional)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblusers_branchId_fkey') THEN
    ALTER TABLE public.tblusers ADD CONSTRAINT "tblusers_branchId_fkey"
      FOREIGN KEY ("branchId") REFERENCES public.tblbranches(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblusers_roleId_fkey') THEN
    ALTER TABLE public.tblusers ADD CONSTRAINT "tblusers_roleId_fkey"
      FOREIGN KEY ("roleId") REFERENCES public.tblrbac(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
END $$;

-- 2.3 Normalized permission dictionary
CREATE TABLE IF NOT EXISTS public.auth_permission_keys (
  id BIGSERIAL PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  module TEXT NOT NULL,
  scope TEXT NOT NULL DEFAULT 'feature',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT auth_permission_keys_scope_check CHECK (scope IN ('feature', 'menu', 'tab', 'action'))
);

-- 2.4 Role -> Permission mapping
CREATE TABLE IF NOT EXISTS public.auth_role_permissions (
  id BIGSERIAL PRIMARY KEY,
  role_id BIGINT NOT NULL REFERENCES public.tblrbac(id) ON DELETE CASCADE,
  permission_id BIGINT NOT NULL REFERENCES public.auth_permission_keys(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(role_id, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_role_permissions_role_id ON public.auth_role_permissions(role_id);
CREATE INDEX IF NOT EXISTS idx_auth_role_permissions_permission_id ON public.auth_role_permissions(permission_id);

-- 2.5 User-level permission overrides (allow/deny)
CREATE TABLE IF NOT EXISTS public.auth_user_permission_overrides (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.tblusers(id) ON DELETE CASCADE,
  permission_id BIGINT NOT NULL REFERENCES public.auth_permission_keys(id) ON DELETE CASCADE,
  effect TEXT NOT NULL,
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT auth_user_permission_overrides_effect_check CHECK (effect IN ('allow', 'deny')),
  UNIQUE(user_id, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_user_permission_overrides_user_id ON public.auth_user_permission_overrides(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_user_permission_overrides_permission_id ON public.auth_user_permission_overrides(permission_id);

-- 2.6 User-role assignments (normalized)
CREATE TABLE IF NOT EXISTS public.auth_user_roles (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.tblusers(id) ON DELETE CASCADE,
  role_id BIGINT NOT NULL REFERENCES public.tblrbac(id) ON DELETE CASCADE,
  is_primary BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_user_roles_user_id ON public.auth_user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_user_roles_role_id ON public.auth_user_roles(role_id);

-- 2.7 Menu registry
CREATE TABLE IF NOT EXISTS public.auth_menus (
  id BIGSERIAL PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  parent_key TEXT,
  route TEXT,
  icon TEXT,
  order_no INT,
  order_index INT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- MODULE 3: INVENTORY (Brands, Products, Capacity, Materials, Parts)
-- ============================================================================

-- 3.1 Brands
CREATE TABLE IF NOT EXISTS public.tblbrands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brandName" VARCHAR NULL,
  prefix VARCHAR NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  type VARCHAR(10) DEFAULT 'ACU' CHECK (type IN ('ACU', 'MAT'))
);

CREATE INDEX IF NOT EXISTS idx_tblbrands_type ON public.tblbrands(type);
COMMENT ON COLUMN public.tblbrands.type IS 'Brand type: ACU for AC Units, MAT for Materials';

-- 3.2 Products (AC Units)
CREATE TABLE IF NOT EXISTS public.tblproducts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brandId" BIGINT NULL,
  "productName" TEXT NULL,
  "productType" VARCHAR NULL,
  "unitTypes" TEXT NULL,
  unit VARCHAR NULL DEFAULT 'SET',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT NULL,
  updated_at TIMESTAMPTZ NULL,
  updated_by BIGINT NULL,
  deleted_at VARCHAR NULL,
  deleted_by BIGINT NULL
);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblproducts_brandId_fkey') THEN
    ALTER TABLE public.tblproducts ADD CONSTRAINT "tblproducts_brandId_fkey"
      FOREIGN KEY ("brandId") REFERENCES public.tblbrands(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
END $$;

-- 3.3 Capacity (per product)
CREATE TABLE IF NOT EXISTS public.tblcapacity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "prodId" BIGINT NULL,
  capacity VARCHAR NULL,
  "indoorModel" VARCHAR NULL,
  "outdoorModel" VARCHAR NULL,
  srp DOUBLE PRECISION NULL DEFAULT 0,
  "netPrice" DOUBLE PRECISION NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "stockCount" BIGINT NULL DEFAULT 0,
  "supplierId" BIGINT NULL,
  "purchaseOrderId" BIGINT NULL,
  "purchaseOrderNo" VARCHAR NULL
);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblcapacity_prodId_fkey') THEN
    ALTER TABLE public.tblcapacity ADD CONSTRAINT "tblcapacity_prodId_fkey"
      FOREIGN KEY ("prodId") REFERENCES public.tblproducts(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
END $$;

-- Capacity additional price fields
DO $$ BEGIN
  ALTER TABLE public.tblcapacity ADD COLUMN IF NOT EXISTS "cashPrice" NUMERIC(12,2) DEFAULT 0;
  ALTER TABLE public.tblcapacity ADD COLUMN IF NOT EXISTS "ccPrice" NUMERIC(12,2) DEFAULT 0;
  ALTER TABLE public.tblcapacity ADD COLUMN IF NOT EXISTS "unitPrice" NUMERIC(12,2) DEFAULT 0;
END $$;

CREATE INDEX IF NOT EXISTS idx_tblcapacity_unitprice ON public.tblcapacity("unitPrice");
CREATE INDEX IF NOT EXISTS idx_tblcapacity_cashprice ON public.tblcapacity("cashPrice");

-- 3.4 Capacity net price history
CREATE TABLE IF NOT EXISTS public.tblcapacity_netprice_history (
  id BIGSERIAL PRIMARY KEY,
  product_id BIGINT NOT NULL,
  capacity VARCHAR(100) NOT NULL,
  net_price NUMERIC(12, 2) NOT NULL,
  supplier_id BIGINT NULL,
  purchase_order_id BIGINT NULL,
  purchase_order_no VARCHAR(100) NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblcapacity_netprice_history_product_id_fkey') THEN
    ALTER TABLE public.tblcapacity_netprice_history ADD CONSTRAINT tblcapacity_netprice_history_product_id_fkey
      FOREIGN KEY (product_id) REFERENCES public.tblproducts(id) ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_netprice_history_lookup ON public.tblcapacity_netprice_history
  USING btree (product_id, capacity, supplier_id, purchase_order_id, purchase_order_no, id DESC);

-- 3.5 Materials (pipes, wires, accessories)
CREATE TABLE IF NOT EXISTS public.tblmaterials (
  id BIGSERIAL PRIMARY KEY,
  brand_id BIGINT NULL REFERENCES public.tblbrands(id) ON UPDATE CASCADE ON DELETE SET NULL,
  material_name TEXT NOT NULL,
  material_code VARCHAR(50) UNIQUE,
  description TEXT,
  unit VARCHAR(20) DEFAULT 'PCS',
  unit_price NUMERIC(12, 2) DEFAULT 0,
  sell_price NUMERIC(12, 2) DEFAULT 0,
  on_hand_stock BIGINT DEFAULT 0,
  reorder_level BIGINT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL,
  updated_at TIMESTAMPTZ,
  updated_by BIGINT REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL,
  deleted_at TIMESTAMPTZ,
  deleted_by BIGINT REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT tblmaterials_material_name_key UNIQUE (material_name)
);

CREATE INDEX IF NOT EXISTS idx_tblmaterials_brand_id ON public.tblmaterials(brand_id);
CREATE INDEX IF NOT EXISTS idx_tblmaterials_deleted_at ON public.tblmaterials(deleted_at);
CREATE INDEX IF NOT EXISTS idx_tblmaterials_on_hand_stock ON public.tblmaterials(on_hand_stock);

COMMENT ON TABLE public.tblmaterials IS 'Material products inventory (pipes, wires, accessories, etc.)';
COMMENT ON COLUMN public.tblmaterials.on_hand_stock IS 'Current available stock quantity';
COMMENT ON COLUMN public.tblmaterials.reorder_level IS 'Alert threshold for low stock';

-- 3.6 Material price history
CREATE TABLE IF NOT EXISTS public.tblmaterial_price_history (
  id BIGSERIAL PRIMARY KEY,
  material_id BIGINT NOT NULL REFERENCES public.tblmaterials(id) ON DELETE CASCADE,
  unit_price NUMERIC(12, 2) NOT NULL,
  sell_price NUMERIC(12, 2) NOT NULL,
  supplier_id UUID,
  purchase_order_id INTEGER,
  purchase_order_no VARCHAR(100),
  created_by BIGINT REFERENCES public.tblusers(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_material_price_history_lookup ON public.tblmaterial_price_history(material_id, id DESC);
COMMENT ON TABLE public.tblmaterial_price_history IS 'Historical tracking of material price changes';

-- 3.7 Material items (ledger-based inventory)
CREATE TABLE IF NOT EXISTS public.tblmaterial_items (
  id BIGSERIAL PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'pcs',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3.8 Product-capacity-material mapping
CREATE TABLE IF NOT EXISTS public.tblproduct_capacity_material_map (
  id BIGSERIAL PRIMARY KEY,
  product_id BIGINT NOT NULL,
  capacity_id BIGINT NOT NULL,
  material_id BIGINT NOT NULL REFERENCES public.tblmaterial_items(id),
  qty_per_set NUMERIC(14, 4) NOT NULL DEFAULT 1,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(product_id, capacity_id, material_id)
);

-- 3.9 Material stock balance
CREATE TABLE IF NOT EXISTS public.tblmaterial_stock_balance (
  id BIGSERIAL PRIMARY KEY,
  material_id BIGINT NOT NULL REFERENCES public.tblmaterial_items(id),
  on_hand NUMERIC(14, 2) NOT NULL DEFAULT 0,
  reserved NUMERIC(14, 2) NOT NULL DEFAULT 0,
  available NUMERIC(14, 2) GENERATED ALWAYS AS (on_hand - reserved) STORED,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(material_id)
);

-- 3.10 Material stock movement ledger
CREATE TABLE IF NOT EXISTS public.tblmaterial_stock_movement (
  id BIGSERIAL PRIMARY KEY,
  material_id BIGINT NOT NULL REFERENCES public.tblmaterial_items(id),
  movement_type TEXT NOT NULL CHECK (movement_type IN ('IN', 'OUT', 'RESERVE', 'RELEASE', 'RETURN', 'ADJUST')),
  qty NUMERIC(14, 2) NOT NULL CHECK (qty > 0),
  source_type TEXT NOT NULL CHECK (source_type IN ('PO', 'SO', 'MANUAL')),
  source_id BIGINT NOT NULL,
  source_line_key TEXT NOT NULL,
  status_snapshot TEXT,
  remarks TEXT,
  created_by BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(source_type, source_id, movement_type, source_line_key)
);

CREATE INDEX IF NOT EXISTS idx_material_stock_movement_source ON public.tblmaterial_stock_movement(source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_material_stock_movement_material ON public.tblmaterial_stock_movement(material_id, created_at DESC);

-- 3.11 Parts (Aircon Parts - motors, fans, boards)
CREATE TABLE IF NOT EXISTS public.tblparts (
  id BIGSERIAL PRIMARY KEY,
  brand_id BIGINT NULL REFERENCES public.tblbrands(id) ON UPDATE CASCADE ON DELETE SET NULL,
  parts_name TEXT NOT NULL,
  model VARCHAR(100),
  parts_code VARCHAR(50) UNIQUE,
  srp NUMERIC(12, 2) DEFAULT 0,
  discount_percentage NUMERIC(5, 2) DEFAULT 0,
  discounted_price NUMERIC(12, 2) DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL,
  updated_at TIMESTAMPTZ,
  updated_by BIGINT REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL,
  deleted_at TIMESTAMPTZ,
  deleted_by BIGINT REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT tblparts_parts_name_key UNIQUE (parts_name, brand_id)
);

CREATE INDEX IF NOT EXISTS idx_tblparts_brand_id ON public.tblparts(brand_id);
CREATE INDEX IF NOT EXISTS idx_tblparts_parts_code ON public.tblparts(parts_code);
CREATE INDEX IF NOT EXISTS idx_tblparts_deleted_at ON public.tblparts(deleted_at);

COMMENT ON TABLE public.tblparts IS 'Aircon Parts inventory (motors, fans, boards, etc.)';

-- ============================================================================
-- MODULE 4: VENDORS & CUSTOMERS
-- ============================================================================

-- 4.1 Vendors (suppliers)
CREATE TABLE IF NOT EXISTS public.tblvendors (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NULL,
  contact_person TEXT NULL,
  contact_number TEXT NULL,
  last_order_date TIMESTAMPTZ NULL
);

-- 4.2 Customers
CREATE TABLE IF NOT EXISTS public.tblcustomer (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NULL,
  contact_number TEXT NULL,
  email TEXT NULL,
  tin_number TEXT NULL,
  contact_person TEXT NULL
);

-- Customer enhancements (sub-dealer support, credit)
DO $$ BEGIN
  ALTER TABLE public.tblcustomer ADD COLUMN IF NOT EXISTS customer_type VARCHAR(20) DEFAULT 'regular';
  ALTER TABLE public.tblcustomer ADD COLUMN IF NOT EXISTS credit_limit NUMERIC(12, 2) DEFAULT 0;
  ALTER TABLE public.tblcustomer ADD COLUMN IF NOT EXISTS current_balance NUMERIC(12, 2) DEFAULT 0;
  ALTER TABLE public.tblcustomer ADD COLUMN IF NOT EXISTS payment_terms INTEGER DEFAULT 0;
  ALTER TABLE public.tblcustomer ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
  ALTER TABLE public.tblcustomer ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblcustomer_customer_type_check') THEN
    ALTER TABLE public.tblcustomer ADD CONSTRAINT tblcustomer_customer_type_check
      CHECK (customer_type IN ('regular', 'sub_dealer'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_tblcustomer_type ON public.tblcustomer(customer_type);

-- 4.3 Customer payments
CREATE TABLE IF NOT EXISTS public.tblcustomer_payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL REFERENCES public.tblcustomer(id) ON UPDATE CASCADE ON DELETE CASCADE,
  sales_id INTEGER,
  payment_amount NUMERIC(12, 2) NOT NULL,
  payment_date DATE NOT NULL,
  payment_method VARCHAR(50),
  reference_no VARCHAR(100),
  payment_notes TEXT,
  applied_to_balance NUMERIC(12, 2) DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_customer_payments_customer_id ON public.tblcustomer_payments(customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_payments_date ON public.tblcustomer_payments(payment_date);

-- 4.4 Statement of Account (SOA)
CREATE TABLE IF NOT EXISTS public.tblstatement_of_account (
  id BIGSERIAL PRIMARY KEY,
  soa_number TEXT GENERATED ALWAYS AS ('SOA-' || LPAD(id::TEXT, 6, '0')) STORED,
  customer_id UUID NOT NULL REFERENCES public.tblcustomer(id) ON UPDATE CASCADE ON DELETE CASCADE,
  period_from DATE NOT NULL,
  period_to DATE NOT NULL,
  opening_balance NUMERIC(12, 2) DEFAULT 0,
  total_charges NUMERIC(12, 2) DEFAULT 0,
  total_payments NUMERIC(12, 2) DEFAULT 0,
  closing_balance NUMERIC(12, 2) DEFAULT 0,
  soa_status VARCHAR(20) DEFAULT 'draft' CHECK (soa_status IN ('draft', 'sent', 'paid', 'overdue')),
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  generated_by BIGINT REFERENCES public.tblusers(id),
  sent_at TIMESTAMPTZ,
  due_date DATE,
  notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_soa_customer_id ON public.tblstatement_of_account(customer_id);
CREATE INDEX IF NOT EXISTS idx_soa_status ON public.tblstatement_of_account(soa_status);
CREATE INDEX IF NOT EXISTS idx_soa_period ON public.tblstatement_of_account(period_from, period_to);

-- ============================================================================
-- MODULE 5: PURCHASE ORDERS
-- ============================================================================

-- 5.1 Purchase orders
CREATE TABLE IF NOT EXISTS public.tblpurchase_orders (
  id SERIAL PRIMARY KEY,
  po_number TEXT GENERATED ALWAYS AS ('PO-' || lpad(id::text, 6, '0')) STORED,
  vendor_id UUID NULL,
  total_amount NUMERIC(12, 2) NULL DEFAULT 0,
  status TEXT NULL DEFAULT 'PENDING',
  created_at TIMESTAMPTZ NULL DEFAULT NOW(),
  created_by BIGINT NULL,
  "branchId" BIGINT NULL
);

-- PO foreign keys
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblpurchase_orders_branchId_fkey') THEN
    ALTER TABLE public.tblpurchase_orders ADD CONSTRAINT "tblpurchase_orders_branchId_fkey"
      FOREIGN KEY ("branchId") REFERENCES public.tblbranches(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblpurchase_orders_created_by_fkey') THEN
    ALTER TABLE public.tblpurchase_orders ADD CONSTRAINT tblpurchase_orders_created_by_fkey
      FOREIGN KEY (created_by) REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblpurchase_orders_vendor_id_fkey') THEN
    ALTER TABLE public.tblpurchase_orders ADD CONSTRAINT tblpurchase_orders_vendor_id_fkey
      FOREIGN KEY (vendor_id) REFERENCES public.tblvendors(id);
  END IF;
END $$;

-- PO additional columns
DO $$ BEGIN
  ALTER TABLE public.tblpurchase_orders ADD COLUMN IF NOT EXISTS po_type VARCHAR(20) DEFAULT 'ACU';
  ALTER TABLE public.tblpurchase_orders ADD COLUMN IF NOT EXISTS linked_sales_order_id INTEGER;
  ALTER TABLE public.tblpurchase_orders ADD COLUMN IF NOT EXISTS "approve_by" BIGINT;
  ALTER TABLE public.tblpurchase_orders ADD COLUMN IF NOT EXISTS "approveDate" TIMESTAMPTZ;
  ALTER TABLE public.tblpurchase_orders ADD COLUMN IF NOT EXISTS "requestType" VARCHAR(50) DEFAULT 'aircon_units';
  ALTER TABLE public.tblpurchase_orders ADD COLUMN IF NOT EXISTS "request_type" VARCHAR(50) DEFAULT 'aircon_units';
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblpurchase_orders_po_type_check') THEN
    ALTER TABLE public.tblpurchase_orders ADD CONSTRAINT tblpurchase_orders_po_type_check
      CHECK (po_type IN ('ACU', 'MATERIAL'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_tblpurchase_orders_po_type ON public.tblpurchase_orders(po_type);
CREATE INDEX IF NOT EXISTS idx_tblpurchase_orders_request_type ON public.tblpurchase_orders("request_type");
CREATE INDEX IF NOT EXISTS idx_tblpurchase_orders_approve_by ON public.tblpurchase_orders("approve_by");

-- 5.2 PO Payments
CREATE TABLE IF NOT EXISTS public.tblpo_payments (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  po_id INTEGER NULL,
  method TEXT NOT NULL,
  payment_date VARCHAR NULL,
  terms BIGINT NULL,
  "termsDueDate" VARCHAR NULL,
  status VARCHAR NULL,
  "paymentDate" VARCHAR NULL,
  "downPayment" NUMERIC NULL
);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblpo_payments_po_id_fkey') THEN
    ALTER TABLE public.tblpo_payments ADD CONSTRAINT tblpo_payments_po_id_fkey
      FOREIGN KEY (po_id) REFERENCES public.tblpurchase_orders(id);
  END IF;
END $$;

-- PO Payments additional columns
DO $$ BEGIN
  ALTER TABLE public.tblpo_payments ADD COLUMN IF NOT EXISTS bank_name TEXT;
  ALTER TABLE public.tblpo_payments ADD COLUMN IF NOT EXISTS reference_no TEXT;
  ALTER TABLE public.tblpo_payments ADD COLUMN IF NOT EXISTS check_no TEXT;
  ALTER TABLE public.tblpo_payments ADD COLUMN IF NOT EXISTS cheque_date TIMESTAMPTZ;
  ALTER TABLE public.tblpo_payments ADD COLUMN IF NOT EXISTS issued_by TEXT;
END $$;

-- 5.3 Process Flow
CREATE TABLE IF NOT EXISTS public.tblprocessflow (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status VARCHAR NULL,
  "nextStep" TEXT NULL,
  "processedBy" BIGINT NULL,
  "stepNo" INTEGER NULL,
  "stepStatus" TEXT NULL,
  "actionStatus" JSON NULL,
  "actionList" JSON NULL
);

-- 5.4 Installation
CREATE TABLE IF NOT EXISTS public.tblinstallation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  installer_id BIGINT NULL,
  members JSONB NULL DEFAULT '[]'::jsonb,
  "workDone" TEXT NULL
);

-- ============================================================================
-- MODULE 6: SALES ORDERS
-- ============================================================================

-- 6.1 Sales Orders
CREATE TABLE IF NOT EXISTS public.tblsales_order (
  id SERIAL PRIMARY KEY,
  so_number TEXT GENERATED ALWAYS AS ('SO-' || lpad(id::text, 6, '0')) STORED,
  customer_id UUID NULL,
  total_amount NUMERIC(12, 2) NULL DEFAULT 0,
  status TEXT NULL DEFAULT 'PENDING',
  created_at TIMESTAMPTZ NULL DEFAULT NOW(),
  created_by BIGINT NULL,
  "branchId" BIGINT NULL,
  "scheduleDate" VARCHAR NULL,
  "salesType" VARCHAR NULL,
  remarks TEXT NULL,
  installer TEXT NULL
);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblsales_order_branchId_fkey') THEN
    ALTER TABLE public.tblsales_order ADD CONSTRAINT "tblsales_order_branchId_fkey"
      FOREIGN KEY ("branchId") REFERENCES public.tblbranches(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblsales_order_customer_id_fkey') THEN
    ALTER TABLE public.tblsales_order ADD CONSTRAINT tblsales_order_customer_id_fkey
      FOREIGN KEY (customer_id) REFERENCES public.tblcustomer(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
END $$;

-- Sales Order additional columns
DO $$ BEGIN
  ALTER TABLE public.tblsales_order ADD COLUMN IF NOT EXISTS project_name TEXT;
  ALTER TABLE public.tblsales_order ADD COLUMN IF NOT EXISTS project_code TEXT;
  ALTER TABLE public.tblsales_order ADD COLUMN IF NOT EXISTS project_id BIGINT;
  ALTER TABLE public.tblsales_order ADD COLUMN IF NOT EXISTS linked_purchase_order_id INTEGER;
END $$;

-- 6.2 SO Payments
CREATE TABLE IF NOT EXISTS public.tblso_payments (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  so_id INTEGER NULL,
  method TEXT NOT NULL,
  terms BIGINT NULL,
  "termsDueDate" VARCHAR NULL,
  status VARCHAR NULL,
  "paymentDate" VARCHAR NULL,
  "referenceNo" VARCHAR NULL,
  "issuedBy" VARCHAR NULL,
  "ccCharge" VARCHAR NULL,
  "checkNo" VARCHAR NULL,
  "bankName" VARCHAR NULL,
  "bankAccount" VARCHAR NULL,
  "downPayment" NUMERIC NULL,
  "postDated" VARCHAR NULL
);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblso_payments_so_id_fkey') THEN
    ALTER TABLE public.tblso_payments ADD CONSTRAINT tblso_payments_so_id_fkey
      FOREIGN KEY (so_id) REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
END $$;

-- SO Payments enhancements
DO $$ BEGIN
  ALTER TABLE public.tblso_payments ADD COLUMN IF NOT EXISTS payment_type VARCHAR(20) DEFAULT 'sales';
  ALTER TABLE public.tblso_payments ADD COLUMN IF NOT EXISTS amount NUMERIC(12, 2) DEFAULT 0;
END $$;

CREATE INDEX IF NOT EXISTS idx_so_payments_type ON public.tblso_payments(payment_type);

-- 6.3 SO Material Items
CREATE TABLE IF NOT EXISTS public.tblso_material_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_id BIGINT NULL,
  cost DOUBLE PRECISION NULL,
  price DOUBLE PRECISION NULL,
  "excessQty" BIGINT NULL,
  "usedQty" BIGINT NULL,
  "inclusionQty" BIGINT NULL,
  sales_id INTEGER NULL
);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblso_material_items_sales_id_fkey') THEN
    ALTER TABLE public.tblso_material_items ADD CONSTRAINT tblso_material_items_sales_id_fkey
      FOREIGN KEY (sales_id) REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
END $$;

-- 6.4 Transaction Product Items (shared PO/SO line items)
CREATE TABLE IF NOT EXISTS public.tbltransaction_product_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transType" VARCHAR NULL,
  "productId" BIGINT NULL,
  "capacityId" BIGINT NULL,
  "unitPrice" DOUBLE PRECISION NULL,
  "sellPrice" DOUBLE PRECISION NULL,
  "discountPrice" DOUBLE PRECISION NULL,
  "unitTypesQty" JSONB NULL DEFAULT '[]'::jsonb,
  "totalSetQty" BIGINT NULL,
  "purchaseId" INTEGER NULL,
  "salesId" BIGINT NULL
);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tbltransaction_product_items_capacityId_fkey') THEN
    ALTER TABLE public.tbltransaction_product_items ADD CONSTRAINT "tbltransaction_product_items_capacityId_fkey"
      FOREIGN KEY ("capacityId") REFERENCES public.tblcapacity(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tbltransaction_product_items_productId_fkey') THEN
    ALTER TABLE public.tbltransaction_product_items ADD CONSTRAINT "tbltransaction_product_items_productId_fkey"
      FOREIGN KEY ("productId") REFERENCES public.tblproducts(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tbltransaction_product_items_purchaseId_fkey') THEN
    ALTER TABLE public.tbltransaction_product_items ADD CONSTRAINT "tbltransaction_product_items_purchaseId_fkey"
      FOREIGN KEY ("purchaseId") REFERENCES public.tblpurchase_orders(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tbltransaction_product_items_salesId_fkey') THEN
    ALTER TABLE public.tbltransaction_product_items ADD CONSTRAINT "tbltransaction_product_items_salesId_fkey"
      FOREIGN KEY ("salesId") REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
END $$;

-- Transaction product items: trans_type normalization
DO $$ BEGIN
  ALTER TABLE public.tbltransaction_product_items ADD COLUMN IF NOT EXISTS trans_type VARCHAR(20) DEFAULT 'purchase';
END $$;

-- 6.5 Transaction Material Items
CREATE TABLE IF NOT EXISTS public.tbltransaction_material_items (
  id BIGSERIAL PRIMARY KEY,
  trans_type VARCHAR(20) NOT NULL CHECK (trans_type IN ('purchase', 'sales')),
  material_id BIGINT NOT NULL REFERENCES public.tblmaterials(id) ON UPDATE CASCADE ON DELETE CASCADE,
  quantity BIGINT NOT NULL DEFAULT 0,
  unit_price NUMERIC(12, 2) DEFAULT 0,
  sell_price NUMERIC(12, 2) DEFAULT 0,
  discount_price NUMERIC(12, 2) DEFAULT 0,
  purchase_id INTEGER REFERENCES public.tblpurchase_orders(id) ON UPDATE CASCADE ON DELETE CASCADE,
  sales_id INTEGER REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_transaction_material_purchase ON public.tbltransaction_material_items(purchase_id);
CREATE INDEX IF NOT EXISTS idx_transaction_material_sales ON public.tbltransaction_material_items(sales_id);
CREATE INDEX IF NOT EXISTS idx_transaction_material_material_id ON public.tbltransaction_material_items(material_id);

-- 6.6 Project Details (per sales order)
CREATE TABLE IF NOT EXISTS public.tblproject_details (
  id BIGSERIAL PRIMARY KEY,
  sales_id INTEGER NOT NULL REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  project_name TEXT NOT NULL,
  project_code VARCHAR(50) UNIQUE,
  project_location TEXT,
  project_start_date DATE,
  project_end_date DATE,
  project_manager TEXT,
  project_status VARCHAR(20) DEFAULT 'ongoing' CHECK (project_status IN ('planning', 'ongoing', 'completed', 'cancelled')),
  project_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT tblproject_details_sales_id_key UNIQUE (sales_id)
);

CREATE INDEX IF NOT EXISTS idx_project_details_sales_id ON public.tblproject_details(sales_id);
CREATE INDEX IF NOT EXISTS idx_project_details_status ON public.tblproject_details(project_status);

-- 6.7 Service Details
CREATE TABLE IF NOT EXISTS public.tblservice_details (
  id BIGSERIAL PRIMARY KEY,
  sales_id INTEGER NOT NULL REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  service_name TEXT NOT NULL,
  service_description TEXT,
  service_type VARCHAR(50),
  technician_assigned TEXT,
  service_date DATE,
  service_duration_hours NUMERIC(5, 2),
  service_cost NUMERIC(12, 2) DEFAULT 0,
  parts_cost NUMERIC(12, 2) DEFAULT 0,
  labor_cost NUMERIC(12, 2) DEFAULT 0,
  service_status VARCHAR(20) DEFAULT 'scheduled' CHECK (service_status IN ('scheduled', 'in_progress', 'completed', 'cancelled')),
  service_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_service_details_sales_id ON public.tblservice_details(sales_id);
CREATE INDEX IF NOT EXISTS idx_service_details_status ON public.tblservice_details(service_status);

-- 6.8 Concern Details
CREATE TABLE IF NOT EXISTS public.tblconcern_details (
  id BIGSERIAL PRIMARY KEY,
  sales_id INTEGER REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  customer_id UUID REFERENCES public.tblcustomer(id) ON UPDATE CASCADE ON DELETE CASCADE,
  concern_type VARCHAR(50),
  concern_subject TEXT NOT NULL,
  concern_description TEXT NOT NULL,
  concern_status VARCHAR(20) DEFAULT 'open',
  priority VARCHAR(20) DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  assigned_to BIGINT REFERENCES public.tblusers(id),
  resolution_notes TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

-- Concern status constraint (expanded values)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblconcern_details_concern_status_check') THEN
    ALTER TABLE public.tblconcern_details ADD CONSTRAINT tblconcern_details_concern_status_check
      CHECK (concern_status IN (
        'open', 'in_progress', 'resolved', 'closed',
        'in-progress', 'reschedule', 'pulled-out', 'warranty', 'void-warranty', 'complete', ''
      ));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_concern_details_sales_id ON public.tblconcern_details(sales_id);
CREATE INDEX IF NOT EXISTS idx_concern_details_customer_id ON public.tblconcern_details(customer_id);
CREATE INDEX IF NOT EXISTS idx_concern_details_status ON public.tblconcern_details(concern_status);

-- 6.9 Transfer Details (branch-to-branch)
CREATE TABLE IF NOT EXISTS public.tbltransfer_details (
  id BIGSERIAL PRIMARY KEY,
  sales_id INTEGER NOT NULL REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  from_branch_id BIGINT NOT NULL REFERENCES public.tblbranches(id),
  to_branch_id BIGINT NOT NULL REFERENCES public.tblbranches(id),
  transfer_date DATE,
  expected_delivery_date DATE,
  actual_delivery_date DATE,
  transfer_status VARCHAR(20) DEFAULT 'pending' CHECK (transfer_status IN ('pending', 'in_transit', 'delivered', 'acknowledged', 'cancelled')),
  sent_by BIGINT REFERENCES public.tblusers(id),
  received_by BIGINT REFERENCES public.tblusers(id),
  acknowledged_by BIGINT REFERENCES public.tblusers(id),
  acknowledged_at TIMESTAMPTZ,
  transfer_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT tbltransfer_details_sales_id_key UNIQUE (sales_id)
);

CREATE INDEX IF NOT EXISTS idx_transfer_details_from_branch ON public.tbltransfer_details(from_branch_id);
CREATE INDEX IF NOT EXISTS idx_transfer_details_to_branch ON public.tbltransfer_details(to_branch_id);
CREATE INDEX IF NOT EXISTS idx_transfer_details_status ON public.tbltransfer_details(transfer_status);

-- 6.10 Expense Details
CREATE TABLE IF NOT EXISTS public.tblexpense_details (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sales_id INTEGER REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  transfer_id BIGINT REFERENCES public.tbltransfer_details(id) ON UPDATE CASCADE ON DELETE CASCADE,
  expense_type VARCHAR(50) NOT NULL,
  expense_description TEXT,
  amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  expense_date DATE,
  paid_to TEXT,
  payment_method VARCHAR(50),
  reference_no VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_expense_details_sales_id ON public.tblexpense_details(sales_id);
CREATE INDEX IF NOT EXISTS idx_expense_details_transfer_id ON public.tblexpense_details(transfer_id);

-- ============================================================================
-- MODULE 7: SERIAL NUMBERS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.tblserial_numbers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branchId" BIGINT NULL,
  "vendorId" UUID NULL,
  "purchaseId" INTEGER NULL,
  "salesId" BIGINT NULL,
  "productId" BIGINT NULL,
  "capacityId" BIGINT NULL,
  "serialNumber" VARCHAR NULL UNIQUE,
  "unitType" VARCHAR NULL,
  status VARCHAR NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT NULL,
  "customerId" UUID NULL
);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblserial_numbers_created_by_fkey') THEN
    ALTER TABLE public.tblserial_numbers ADD CONSTRAINT tblserial_numbers_created_by_fkey
      FOREIGN KEY (created_by) REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblserial_numbers_customerId_fkey') THEN
    ALTER TABLE public.tblserial_numbers ADD CONSTRAINT "tblserial_numbers_customerId_fkey"
      FOREIGN KEY ("customerId") REFERENCES public.tblcustomer(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblserial_numbers_productId_fkey') THEN
    ALTER TABLE public.tblserial_numbers ADD CONSTRAINT "tblserial_numbers_productId_fkey"
      FOREIGN KEY ("productId") REFERENCES public.tblproducts(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblserial_numbers_purchaseId_fkey') THEN
    ALTER TABLE public.tblserial_numbers ADD CONSTRAINT "tblserial_numbers_purchaseId_fkey"
      FOREIGN KEY ("purchaseId") REFERENCES public.tblpurchase_orders(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblserial_numbers_salesId_fkey') THEN
    ALTER TABLE public.tblserial_numbers ADD CONSTRAINT "tblserial_numbers_salesId_fkey"
      FOREIGN KEY ("salesId") REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblserial_numbers_branchId_fkey') THEN
    ALTER TABLE public.tblserial_numbers ADD CONSTRAINT "tblserial_numbers_branchId_fkey"
      FOREIGN KEY ("branchId") REFERENCES public.tblbranches(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblserial_numbers_vendorId_fkey') THEN
    ALTER TABLE public.tblserial_numbers ADD CONSTRAINT "tblserial_numbers_vendorId_fkey"
      FOREIGN KEY ("vendorId") REFERENCES public.tblvendors(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblserial_numbers_capacityId_fkey') THEN
    ALTER TABLE public.tblserial_numbers ADD CONSTRAINT "tblserial_numbers_capacityId_fkey"
      FOREIGN KEY ("capacityId") REFERENCES public.tblcapacity(id) ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
END $$;

-- Serial number defect/return fields
DO $$ BEGIN
  ALTER TABLE public.tblserial_numbers ADD COLUMN IF NOT EXISTS "isDefective" BOOLEAN DEFAULT FALSE;
  ALTER TABLE public.tblserial_numbers ADD COLUMN IF NOT EXISTS "isReturned" BOOLEAN DEFAULT FALSE;
  ALTER TABLE public.tblserial_numbers ADD COLUMN IF NOT EXISTS "defectReason" TEXT;
  ALTER TABLE public.tblserial_numbers ADD COLUMN IF NOT EXISTS "returnReason" TEXT;
  ALTER TABLE public.tblserial_numbers ADD COLUMN IF NOT EXISTS "defectDate" TIMESTAMPTZ;
  ALTER TABLE public.tblserial_numbers ADD COLUMN IF NOT EXISTS "returnDate" TIMESTAMPTZ;
  ALTER TABLE public.tblserial_numbers ADD COLUMN IF NOT EXISTS "previousSalesId" BIGINT;
END $$;

CREATE INDEX IF NOT EXISTS idx_tblserial_numbers_isDefective ON public.tblserial_numbers("isDefective") WHERE "isDefective" = true;
CREATE INDEX IF NOT EXISTS idx_tblserial_numbers_isReturned ON public.tblserial_numbers("isReturned") WHERE "isReturned" = true;

-- ============================================================================
-- MODULE 8: QUOTATIONS
-- ============================================================================

-- 8.1 Quotation header
CREATE TABLE IF NOT EXISTS public.tblquotation (
  id BIGSERIAL PRIMARY KEY,
  quote_no TEXT NOT NULL UNIQUE,
  quote_date DATE NOT NULL DEFAULT CURRENT_DATE,
  customer_id UUID REFERENCES public.tblcustomer(id) ON DELETE SET NULL,
  customer_name TEXT,
  customer_address TEXT,
  customer_contact_person TEXT,
  customer_contact_number TEXT,
  customer_email TEXT,
  customer_tin_number TEXT,
  total_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'draft',
  remarks TEXT,
  converted_sales_id BIGINT,
  created_by BIGINT REFERENCES public.tblusers(id) ON DELETE SET NULL,
  branch_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Quotation additional columns
DO $$ BEGIN
  ALTER TABLE public.tblquotation ADD COLUMN IF NOT EXISTS terms_conditions JSONB NOT NULL DEFAULT '{}'::jsonb;
  ALTER TABLE public.tblquotation ADD COLUMN IF NOT EXISTS validity_days INTEGER NOT NULL DEFAULT 14;
  ALTER TABLE public.tblquotation ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
  ALTER TABLE public.tblquotation ADD COLUMN IF NOT EXISTS expired_at TIMESTAMPTZ;
  ALTER TABLE public.tblquotation ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
  ALTER TABLE public.tblquotation ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
END $$;

-- Status constraint (includes expired)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblquotation_status_check') THEN
    ALTER TABLE public.tblquotation ADD CONSTRAINT tblquotation_status_check
      CHECK (LOWER(status) IN ('draft', 'finalized', 'converted', 'cancelled', 'expired'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_tblquotation_customer_id ON public.tblquotation(customer_id);
CREATE INDEX IF NOT EXISTS idx_tblquotation_status ON public.tblquotation(status);
CREATE INDEX IF NOT EXISTS idx_tblquotation_quote_date ON public.tblquotation(quote_date);
CREATE INDEX IF NOT EXISTS idx_tblquotation_created_at ON public.tblquotation(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tblquotation_is_deleted ON public.tblquotation(is_deleted);
CREATE INDEX IF NOT EXISTS idx_tblquotation_expires_at ON public.tblquotation(expires_at);

-- 8.2 Quotation line items
CREATE TABLE IF NOT EXISTS public.tblquotation_items (
  id BIGSERIAL PRIMARY KEY,
  quotation_id BIGINT NOT NULL REFERENCES public.tblquotation(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.tblproducts(id) ON DELETE SET NULL,
  capacity_id BIGINT REFERENCES public.tblcapacity(id) ON DELETE SET NULL,
  unit_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  sell_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  discount_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  unit_types_qty JSONB NOT NULL DEFAULT '[]'::jsonb,
  total_set_qty INTEGER NOT NULL DEFAULT 0,
  line_total NUMERIC(14, 2) NOT NULL DEFAULT 0,
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tblquotation_items_quotation_id ON public.tblquotation_items(quotation_id);
CREATE INDEX IF NOT EXISTS idx_tblquotation_items_product_id ON public.tblquotation_items(product_id);
CREATE INDEX IF NOT EXISTS idx_tblquotation_items_capacity_id ON public.tblquotation_items(capacity_id);

-- ============================================================================
-- MODULE 9: PROJECTS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.tblprojects (
  id BIGSERIAL PRIMARY KEY,
  project_code VARCHAR(50) UNIQUE NOT NULL,
  project_name TEXT NOT NULL,
  project_type VARCHAR(50),
  project_owner TEXT,
  project_owner_id BIGINT REFERENCES public.tblusers(id) ON DELETE SET NULL,
  project_location TEXT,
  project_start_date DATE,
  project_end_date DATE,
  project_manager TEXT,
  project_manager_id BIGINT REFERENCES public.tblusers(id) ON DELETE SET NULL,
  project_status VARCHAR(20) NOT NULL DEFAULT 'planning' CHECK (project_status IN ('planning', 'ongoing', 'completed', 'cancelled')),
  project_notes TEXT,
  branch_id BIGINT,
  created_by BIGINT REFERENCES public.tblusers(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tblprojects_project_code ON public.tblprojects(project_code);
CREATE INDEX IF NOT EXISTS idx_tblprojects_project_name ON public.tblprojects(project_name);
CREATE INDEX IF NOT EXISTS idx_tblprojects_project_status ON public.tblprojects(project_status);
CREATE INDEX IF NOT EXISTS idx_tblprojects_branch_id ON public.tblprojects(branch_id);
CREATE INDEX IF NOT EXISTS idx_tblprojects_project_owner_id ON public.tblprojects(project_owner_id);

-- Link sales order to project
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tblsales_order_project_id_fkey') THEN
    ALTER TABLE public.tblsales_order ADD CONSTRAINT tblsales_order_project_id_fkey
      FOREIGN KEY (project_id) REFERENCES public.tblprojects(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_tblsales_order_project_id ON public.tblsales_order(project_id);

COMMENT ON TABLE public.tblprojects IS 'Master table for project definitions; supports multiple sales orders per project for staggered unit releases';

-- ============================================================================
-- MODULE 10: ACCOUNTING (Cheque Vouchers, General Journal, Tax)
-- ============================================================================

-- 10.1 Account Titles (Chart of Accounts)
CREATE TABLE IF NOT EXISTS public.tblaccount_titles (
  id BIGSERIAL PRIMARY KEY,
  account_number VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tblaccount_titles_number_description
  ON public.tblaccount_titles (account_number, description);

-- 10.2 Cheque Vouchers
CREATE TABLE IF NOT EXISTS public.tblcheque_vouchers (
  id BIGSERIAL PRIMARY KEY,
  cv_no VARCHAR(32) NOT NULL UNIQUE,
  voucher_type VARCHAR(120) NOT NULL,
  payee TEXT NOT NULL DEFAULT '',
  voucher_date DATE NOT NULL,
  tin_number TEXT,
  address TEXT,
  zip_code TEXT,
  particulars TEXT,
  prepared_by TEXT,
  released_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tblcheque_vouchers_voucher_date ON public.tblcheque_vouchers(voucher_date);

-- 10.3 Cheque Voucher Deposits
CREATE TABLE IF NOT EXISTS public.tblcheque_voucher_deposits (
  id BIGSERIAL PRIMARY KEY,
  voucher_id BIGINT NOT NULL REFERENCES public.tblcheque_vouchers(id) ON DELETE CASCADE,
  bank_name TEXT,
  cheque_no TEXT,
  cheque_date DATE,
  amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tblcheque_voucher_deposits_voucher_id ON public.tblcheque_voucher_deposits(voucher_id);

-- 10.4 Cheque Voucher Invoices
CREATE TABLE IF NOT EXISTS public.tblcheque_voucher_invoices (
  id BIGSERIAL PRIMARY KEY,
  voucher_id BIGINT NOT NULL REFERENCES public.tblcheque_vouchers(id) ON DELETE CASCADE,
  invoice_no TEXT,
  invoice_date DATE,
  description TEXT,
  amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tblcheque_voucher_invoices_voucher_id ON public.tblcheque_voucher_invoices(voucher_id);

-- 10.5 Cheque Voucher Account Titles (debit/credit lines)
CREATE TABLE IF NOT EXISTS public.tblcheque_voucher_account_titles (
  id BIGSERIAL PRIMARY KEY,
  voucher_id BIGINT NOT NULL REFERENCES public.tblcheque_vouchers(id) ON DELETE CASCADE,
  account_title_id BIGINT REFERENCES public.tblaccount_titles(id),
  account_number VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  debit NUMERIC(14,2) NOT NULL DEFAULT 0,
  credit NUMERIC(14,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tblcheque_voucher_account_titles_voucher_id ON public.tblcheque_voucher_account_titles(voucher_id);

-- 10.6 Accounting Report Print Settings
CREATE TABLE IF NOT EXISTS public.tblaccounting_report_print_settings (
  id BIGSERIAL PRIMARY KEY,
  report_key TEXT NOT NULL,
  branch_id BIGINT NOT NULL DEFAULT 0,
  settings_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tblaccounting_report_print_settings_report_branch
  ON public.tblaccounting_report_print_settings (report_key, branch_id);
CREATE INDEX IF NOT EXISTS idx_tblaccounting_report_print_settings_report_key
  ON public.tblaccounting_report_print_settings (report_key);

-- 10.7 General Journal
CREATE TABLE IF NOT EXISTS public.tblgeneral_journal (
  id BIGSERIAL PRIMARY KEY,
  journal_number TEXT GENERATED ALWAYS AS ('JE-' || LPAD(id::TEXT, 6, '0')) STORED,
  journal_date DATE NOT NULL,
  reference_type VARCHAR(50),
  reference_id INTEGER,
  reference_number TEXT,
  description TEXT NOT NULL,
  total_debit NUMERIC(12, 2) DEFAULT 0,
  total_credit NUMERIC(12, 2) DEFAULT 0,
  status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'posted', 'reversed')),
  posted_at TIMESTAMPTZ,
  posted_by BIGINT REFERENCES public.tblusers(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_general_journal_date ON public.tblgeneral_journal(journal_date);
CREATE INDEX IF NOT EXISTS idx_general_journal_status ON public.tblgeneral_journal(status);
CREATE INDEX IF NOT EXISTS idx_general_journal_reference ON public.tblgeneral_journal(reference_type, reference_id);

-- 10.8 Journal Entry Lines
CREATE TABLE IF NOT EXISTS public.tbljournal_entry_lines (
  id BIGSERIAL PRIMARY KEY,
  journal_id BIGINT NOT NULL REFERENCES public.tblgeneral_journal(id) ON DELETE CASCADE,
  line_number INTEGER NOT NULL,
  account_code VARCHAR(50) NOT NULL,
  account_name TEXT NOT NULL,
  description TEXT,
  debit_amount NUMERIC(12, 2) DEFAULT 0,
  credit_amount NUMERIC(12, 2) DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_journal_lines_journal_id ON public.tbljournal_entry_lines(journal_id);
CREATE INDEX IF NOT EXISTS idx_journal_lines_account ON public.tbljournal_entry_lines(account_code);

-- 10.9 BIR 2307 Tax Report
CREATE TABLE IF NOT EXISTS public.tbltax_2307 (
  id BIGSERIAL PRIMARY KEY,
  tax_year INTEGER NOT NULL,
  tax_quarter INTEGER CHECK (tax_quarter BETWEEN 1 AND 4),
  tax_month INTEGER CHECK (tax_month BETWEEN 1 AND 12),
  payee_name TEXT NOT NULL,
  payee_tin VARCHAR(50) NOT NULL,
  payee_address TEXT,
  income_payment_type VARCHAR(100),
  atc_code VARCHAR(10),
  gross_amount NUMERIC(12, 2) NOT NULL,
  tax_rate NUMERIC(5, 2) NOT NULL,
  tax_withheld NUMERIC(12, 2) NOT NULL,
  payment_date DATE,
  reference_type VARCHAR(50),
  reference_id INTEGER,
  reference_number TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_tax_2307_year_quarter ON public.tbltax_2307(tax_year, tax_quarter);
CREATE INDEX IF NOT EXISTS idx_tax_2307_payee_tin ON public.tbltax_2307(payee_tin);
CREATE INDEX IF NOT EXISTS idx_tax_2307_date ON public.tbltax_2307(payment_date);

COMMENT ON TABLE public.tbltax_2307 IS 'BIR Form 2307 - Certificate of Creditable Tax Withheld at Source';

-- 10.10 Legacy Cheque Voucher (from material inventory migration)
CREATE TABLE IF NOT EXISTS public.tblcheque_voucher (
  id BIGSERIAL PRIMARY KEY,
  cv_number TEXT GENERATED ALWAYS AS ('CV-' || LPAD(id::TEXT, 6, '0')) STORED,
  payee_name TEXT NOT NULL,
  payee_address TEXT,
  payee_tin VARCHAR(50),
  cheque_number VARCHAR(50),
  bank_name VARCHAR(100),
  cheque_date DATE,
  amount NUMERIC(12, 2) NOT NULL,
  amount_in_words TEXT,
  particulars TEXT NOT NULL,
  account_code VARCHAR(50),
  category VARCHAR(50),
  payment_type VARCHAR(50),
  status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'issued', 'cleared', 'cancelled')),
  approved_by BIGINT REFERENCES public.tblusers(id),
  approved_at TIMESTAMPTZ,
  issued_by BIGINT REFERENCES public.tblusers(id),
  issued_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id),
  updated_at TIMESTAMPTZ,
  updated_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_cheque_voucher_status ON public.tblcheque_voucher(status);
CREATE INDEX IF NOT EXISTS idx_cheque_voucher_date ON public.tblcheque_voucher(cheque_date);

-- ============================================================================
-- MODULE 11: PAYROLL
-- ============================================================================

-- 11.1 Payroll Employees
CREATE TABLE IF NOT EXISTS public.tblpayroll_employees (
  id BIGSERIAL PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  position VARCHAR(100) NOT NULL,
  project_id BIGINT,
  base_salary NUMERIC(12,2) NOT NULL CHECK (base_salary > 0),
  status SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  created_by BIGINT REFERENCES public.tblusers(id)
);

-- Payroll employee enhancements (government deductions, department)
DO $$ BEGIN
  ALTER TABLE public.tblpayroll_employees ADD COLUMN IF NOT EXISTS pag_ibig NUMERIC(12,2) NOT NULL DEFAULT 0;
  ALTER TABLE public.tblpayroll_employees ADD COLUMN IF NOT EXISTS philhealth NUMERIC(12,2) NOT NULL DEFAULT 0;
  ALTER TABLE public.tblpayroll_employees ADD COLUMN IF NOT EXISTS sss NUMERIC(12,2) NOT NULL DEFAULT 0;
  ALTER TABLE public.tblpayroll_employees ADD COLUMN IF NOT EXISTS contact_number VARCHAR(50);
  ALTER TABLE public.tblpayroll_employees ADD COLUMN IF NOT EXISTS address TEXT;
  ALTER TABLE public.tblpayroll_employees ADD COLUMN IF NOT EXISTS department VARCHAR(50) NOT NULL DEFAULT 'Office';
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_pag_ibig_non_negative') THEN
    ALTER TABLE public.tblpayroll_employees ADD CONSTRAINT chk_pag_ibig_non_negative CHECK (pag_ibig >= 0);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_philhealth_non_negative') THEN
    ALTER TABLE public.tblpayroll_employees ADD CONSTRAINT chk_philhealth_non_negative CHECK (philhealth >= 0);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_sss_non_negative') THEN
    ALTER TABLE public.tblpayroll_employees ADD CONSTRAINT chk_sss_non_negative CHECK (sss >= 0);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_department_values') THEN
    ALTER TABLE public.tblpayroll_employees ADD CONSTRAINT chk_department_values
      CHECK (department IN ('Driver', 'Installer', 'Helper', 'Office', 'Project Assigned'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_payroll_employees_position ON public.tblpayroll_employees(position);
CREATE INDEX IF NOT EXISTS idx_payroll_employees_project ON public.tblpayroll_employees(project_id);

-- 11.2 Payroll Cutoffs
CREATE TABLE IF NOT EXISTS public.tblpayroll_cutoffs (
  id BIGSERIAL PRIMARY KEY,
  cutoff_start DATE NOT NULL,
  cutoff_end DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id),
  CONSTRAINT chk_cutoff_dates CHECK (cutoff_end >= cutoff_start)
);

-- 11.3 Payroll Records
CREATE TABLE IF NOT EXISTS public.tblpayroll_records (
  id BIGSERIAL PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES public.tblpayroll_employees(id) ON DELETE CASCADE,
  cutoff_id BIGINT NOT NULL REFERENCES public.tblpayroll_cutoffs(id) ON DELETE CASCADE,
  base_salary_used NUMERIC(12,2) NOT NULL,
  payout_amount NUMERIC(12,2) NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_employee_cutoff UNIQUE (employee_id, cutoff_id)
);

-- Payroll records enhancements
DO $$ BEGIN
  ALTER TABLE public.tblpayroll_records ADD COLUMN IF NOT EXISTS pag_ibig_used NUMERIC(12,2) NOT NULL DEFAULT 0;
  ALTER TABLE public.tblpayroll_records ADD COLUMN IF NOT EXISTS philhealth_used NUMERIC(12,2) NOT NULL DEFAULT 0;
  ALTER TABLE public.tblpayroll_records ADD COLUMN IF NOT EXISTS sss_used NUMERIC(12,2) NOT NULL DEFAULT 0;
  ALTER TABLE public.tblpayroll_records ADD COLUMN IF NOT EXISTS total_commissions NUMERIC(12,2) NOT NULL DEFAULT 0;
END $$;

CREATE INDEX IF NOT EXISTS idx_payroll_records_employee ON public.tblpayroll_records(employee_id);
CREATE INDEX IF NOT EXISTS idx_payroll_records_cutoff ON public.tblpayroll_records(cutoff_id);

-- 11.4 Payroll Daily Records
CREATE TABLE IF NOT EXISTS public.tblpayroll_daily_records (
  id BIGSERIAL PRIMARY KEY,
  payroll_record_id BIGINT NOT NULL REFERENCES public.tblpayroll_records(id) ON DELETE CASCADE,
  record_date DATE NOT NULL,
  is_present BOOLEAN NOT NULL DEFAULT FALSE,
  assigned_project_id BIGINT,
  commission NUMERIC(12,2) NOT NULL DEFAULT 0,
  remarks TEXT,
  CONSTRAINT uq_daily_record_date UNIQUE (payroll_record_id, record_date)
);

-- Daily records enhancements
DO $$ BEGIN
  ALTER TABLE public.tblpayroll_daily_records ADD COLUMN IF NOT EXISTS adjusted_rate NUMERIC(12,2) NOT NULL DEFAULT 0;
  ALTER TABLE public.tblpayroll_daily_records ADD COLUMN IF NOT EXISTS overtime NUMERIC DEFAULT 0;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_adjusted_rate_non_negative') THEN
    ALTER TABLE public.tblpayroll_daily_records ADD CONSTRAINT chk_adjusted_rate_non_negative CHECK (adjusted_rate >= 0);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_daily_records_payroll ON public.tblpayroll_daily_records(payroll_record_id);

-- 11.5 Payroll Additional Compensation
CREATE TABLE IF NOT EXISTS public.tblpayroll_additional_compensation (
  id BIGSERIAL PRIMARY KEY,
  payroll_record_id BIGINT NOT NULL REFERENCES public.tblpayroll_records(id) ON DELETE CASCADE,
  description VARCHAR(255) NOT NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_additional_comp_payroll ON public.tblpayroll_additional_compensation(payroll_record_id);

-- 11.6 Payroll Additional Deductions
CREATE TABLE IF NOT EXISTS public.tblpayroll_additional_deductions (
  id BIGSERIAL PRIMARY KEY,
  payroll_record_id BIGINT NOT NULL REFERENCES public.tblpayroll_records(id) ON DELETE CASCADE,
  description VARCHAR(255) NOT NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_additional_ded_payroll ON public.tblpayroll_additional_deductions(payroll_record_id);

-- ============================================================================
-- MODULE 12: AUDIT LOGS
-- ============================================================================

-- 12.1 Audit Logs (action-based)
CREATE TABLE IF NOT EXISTS public.tblaudit_logs (
  id BIGSERIAL PRIMARY KEY,
  action VARCHAR(100) NOT NULL,
  entity_type VARCHAR(100) NOT NULL,
  entity_id VARCHAR(100),
  user_id INTEGER,
  username VARCHAR(150),
  role_name VARCHAR(100),
  branch_id INTEGER,
  ip_address VARCHAR(60),
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON public.tblaudit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON public.tblaudit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON public.tblaudit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.tblaudit_logs(created_at DESC);

-- 12.2 Audit Log (change-tracking based)
CREATE TABLE IF NOT EXISTS public.tblaudit_log (
  id BIGSERIAL PRIMARY KEY,
  table_name VARCHAR(100) NOT NULL,
  record_id TEXT NOT NULL,
  action VARCHAR(20) NOT NULL CHECK (action IN ('CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'CANCEL')),
  old_values JSONB,
  new_values JSONB,
  changed_by BIGINT REFERENCES public.tblusers(id),
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ip_address VARCHAR(50),
  user_agent TEXT
);

CREATE INDEX IF NOT EXISTS idx_audit_log_table_record ON public.tblaudit_log(table_name, record_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_changed_by ON public.tblaudit_log(changed_by);
CREATE INDEX IF NOT EXISTS idx_audit_log_changed_at ON public.tblaudit_log(changed_at);

-- ============================================================================
-- MODULE 13: TRIGGERS & FUNCTIONS
-- ============================================================================

-- 13.1 Generic updated_at trigger function
CREATE OR REPLACE FUNCTION public.set_current_timestamp_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- 13.2 Quotation auto quote_no generation
CREATE OR REPLACE FUNCTION public.tblquotation_set_quote_no()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.id IS NULL THEN
    NEW.id := nextval(pg_get_serial_sequence('public.tblquotation', 'id'));
  END IF;

  IF NEW.quote_no IS NULL OR btrim(NEW.quote_no) = '' THEN
    NEW.quote_no :=
      'QT-' ||
      to_char(COALESCE(NEW.quote_date, CURRENT_DATE), 'YYYYMMDD') ||
      '-' ||
      lpad(NEW.id::text, 6, '0');
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tblquotation_set_quote_no ON public.tblquotation;
CREATE TRIGGER trg_tblquotation_set_quote_no
BEFORE INSERT ON public.tblquotation
FOR EACH ROW EXECUTE FUNCTION public.tblquotation_set_quote_no();

-- 13.3 Quotation updated_at triggers
DROP TRIGGER IF EXISTS trg_tblquotation_updated_at ON public.tblquotation;
CREATE TRIGGER trg_tblquotation_updated_at
BEFORE UPDATE ON public.tblquotation
FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();

DROP TRIGGER IF EXISTS trg_tblquotation_items_updated_at ON public.tblquotation_items;
CREATE TRIGGER trg_tblquotation_items_updated_at
BEFORE UPDATE ON public.tblquotation_items
FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();

-- 13.4 Projects updated_at trigger
DROP TRIGGER IF EXISTS trg_tblprojects_updated_at ON public.tblprojects;
CREATE TRIGGER trg_tblprojects_updated_at
BEFORE UPDATE ON public.tblprojects
FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();

-- 13.5 Material stock update on PO approval/completion
CREATE OR REPLACE FUNCTION public.update_material_stock_on_po_approval()
RETURNS TRIGGER AS $$
BEGIN
  IF (NEW.po_type IN ('ACM', 'MATERIAL'))
     AND (UPPER(NEW.status) IN ('APPROVED', 'COMPLETED', 'REQUEST_COMPLETED'))
     AND (UPPER(COALESCE(OLD.status, '')) NOT IN ('APPROVED', 'COMPLETED', 'REQUEST_COMPLETED'))
  THEN
    UPDATE public.tblmaterials m
    SET on_hand_stock = on_hand_stock + tmi.quantity,
        updated_at = NOW()
    FROM public.tbltransaction_material_items tmi
    WHERE tmi.purchase_id = NEW.id
      AND tmi.material_id = m.id
      AND tmi.trans_type = 'purchase';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_material_stock_on_po_approval ON public.tblpurchase_orders;
CREATE TRIGGER trg_update_material_stock_on_po_approval
  AFTER UPDATE ON public.tblpurchase_orders
  FOR EACH ROW
  EXECUTE FUNCTION public.update_material_stock_on_po_approval();

-- 13.6 Customer balance recalculation
CREATE OR REPLACE FUNCTION public.recalc_customer_balance(p_customer_id UUID)
RETURNS VOID AS $$
BEGIN
  UPDATE public.tblcustomer
  SET current_balance = (
    COALESCE(
      (SELECT SUM(total_amount) FROM public.tblsales_order WHERE customer_id = p_customer_id), 0
    )
    - COALESCE(
      (SELECT SUM(payment_amount) FROM public.tblcustomer_payments WHERE customer_id = p_customer_id), 0
    )
    - COALESCE(
      (
        SELECT SUM(COALESCE(sp.amount, 0))
        FROM public.tblso_payments sp
        JOIN public.tblsales_order so ON so.id = sp.so_id
        WHERE so.customer_id = p_customer_id
          AND LOWER(COALESCE(sp.status, 'paid')) = 'paid'
          AND LOWER(COALESCE(sp.payment_type, 'sales')) = 'sales'
      ), 0
    )
  ),
  updated_at = NOW()
  WHERE id = p_customer_id;
END;
$$ LANGUAGE plpgsql;

-- 13.7 Customer balance triggers
CREATE OR REPLACE FUNCTION public.update_customer_balance_on_sales()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.customer_id IS NOT NULL THEN
    PERFORM public.recalc_customer_balance(NEW.customer_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_customer_balance_on_sales ON public.tblsales_order;
CREATE TRIGGER trg_update_customer_balance_on_sales
  AFTER INSERT OR UPDATE ON public.tblsales_order
  FOR EACH ROW
  EXECUTE FUNCTION public.update_customer_balance_on_sales();

CREATE OR REPLACE FUNCTION public.update_customer_balance_on_customer_payment()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.customer_id IS NOT NULL THEN
    PERFORM public.recalc_customer_balance(NEW.customer_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_customer_balance_on_payment ON public.tblcustomer_payments;
CREATE TRIGGER trg_update_customer_balance_on_payment
  AFTER INSERT OR UPDATE ON public.tblcustomer_payments
  FOR EACH ROW
  EXECUTE FUNCTION public.update_customer_balance_on_customer_payment();

CREATE OR REPLACE FUNCTION public.update_customer_balance_on_so_payment()
RETURNS TRIGGER AS $$
DECLARE
  v_customer_id UUID;
BEGIN
  SELECT customer_id INTO v_customer_id FROM public.tblsales_order WHERE id = NEW.so_id;
  IF v_customer_id IS NOT NULL THEN
    PERFORM public.recalc_customer_balance(v_customer_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_customer_balance_on_so_payment ON public.tblso_payments;
CREATE TRIGGER trg_update_customer_balance_on_so_payment
  AFTER INSERT OR UPDATE ON public.tblso_payments
  FOR EACH ROW
  EXECUTE FUNCTION public.update_customer_balance_on_so_payment();

-- ============================================================================
-- MODULE 14: SEED DATA (RBAC Permissions, Roles, Menus, Default Users)
-- ============================================================================

-- 14.1 Seed Roles
INSERT INTO public.tblrbac (id, "roleName", "roleMenus", "rolePermission", created_by)
VALUES
  (1, 'superadmin', 'ALL', 'ALL', NULL),
  (2, 'admin', 'dashboard,projects,sales,inventory,settings,accounting,payroll', 'ALL', NULL),
  (3, 'Business Owner', 'ALL', 'ALL', NULL),
  (4, 'sales', 'dashboard,projects,sales', 'projects.view,sales.view', NULL),
  (5, 'user', 'dashboard', 'projects.view', NULL)
ON CONFLICT (id) DO NOTHING;

-- Reset sequence
SELECT setval(pg_get_serial_sequence('public.tblrbac', 'id'), GREATEST(5, (SELECT MAX(id) FROM public.tblrbac)));

-- 14.2 Seed Menus
INSERT INTO public.auth_menus (key, label, parent_key, route, icon, order_no)
VALUES
  ('dashboard', 'Dashboard', NULL, '/dashboard', 'dashboard', 1),
  ('projects', 'Projects', NULL, '/projects', 'folder', 2),
  ('sales', 'Sales Orders', NULL, '/sales', 'shopping_cart', 3),
  ('inventory', 'Inventory', NULL, '/inventory', 'inventory', 4),
  ('quotation', 'Quotations', NULL, '/quotation', 'request_quote', 5),
  ('accounting', 'Accounting', NULL, '/accounting', 'account_balance', 6),
  ('payroll', 'Payroll', NULL, '/payroll', 'payments', 7),
  ('settings', 'Settings', NULL, '/settings', 'settings', 99)
ON CONFLICT (key) DO NOTHING;

-- 14.3 Seed Permission Keys (all modules)
INSERT INTO public.auth_permission_keys(key, label, module, scope)
VALUES
  -- Dashboard
  ('dashboard.view', 'View Dashboard', 'dashboard', 'feature'),

  -- Projects
  ('projects.view', 'View Projects', 'projects', 'feature'),
  ('projects.create', 'Create Project', 'projects', 'action'),
  ('projects.edit', 'Edit Project', 'projects', 'action'),
  ('projects.delete', 'Delete Project', 'projects', 'action'),
  ('legacy.menu.projects', 'Legacy Menu: Projects', 'legacy', 'menu'),

  -- Sales
  ('sales.view', 'View Sales Orders', 'sales', 'feature'),
  ('sales.create', 'Create Sales Order', 'sales', 'action'),
  ('sales.edit', 'Edit Sales Order', 'sales', 'action'),
  ('sales.delete', 'Delete Sales Order', 'sales', 'action'),

  -- Inventory
  ('inventory.view', 'View Inventory', 'inventory', 'feature'),
  ('inventory.land-costing.view', 'Inventory: View Land Costing Report', 'inventory', 'feature'),
  ('inventory.land-costing.margin.view', 'Inventory: View Land Costing Margin', 'inventory', 'feature'),
  ('inventory.land-costing.export', 'Inventory: Export Land Costing Report', 'inventory', 'action'),

  -- Settings
  ('settings.view', 'View Settings', 'settings', 'feature'),
  ('settings.edit', 'Edit Settings', 'settings', 'action'),

  -- Quotation
  ('quotation.view', 'View Quotations', 'quotation', 'feature'),
  ('quotation.create', 'Create Quotation', 'quotation', 'action'),
  ('quotation.edit', 'Edit Quotation', 'quotation', 'action'),
  ('quotation.finalize', 'Finalize Quotation', 'quotation', 'action'),
  ('quotation.convert', 'Convert Quotation to SO', 'quotation', 'action'),
  ('quotation.print', 'Print Quotation', 'quotation', 'action'),
  ('legacy.menu.quotation', 'Legacy Menu: quotation', 'legacy', 'menu'),

  -- Accounting
  ('accounting.view', 'View Accounting Module', 'accounting', 'feature'),
  ('accounting.report.cheque-voucher.view', 'Accounting Report: Cheque Voucher', 'accounting', 'feature'),
  ('accounting.report.general-journal-register.view', 'Accounting Report: General Journal Register', 'accounting', 'feature'),
  ('accounting.report.disbursement-register.view', 'Accounting Report: Disbursement Register', 'accounting', 'feature'),
  ('accounting.report.sales-register.view', 'Accounting Report: Sales Register', 'accounting', 'feature'),
  ('accounting.report.tax-2307-report.view', 'Accounting Report: 2307 Tax Report', 'accounting', 'feature'),
  ('accounting.report.weekly-sales.view', 'Accounting Report: Weekly Sales', 'accounting', 'feature'),
  ('accounting.report.daily-unit-released.view', 'Accounting Report: Daily Unit Released', 'accounting', 'feature'),
  ('accounting.report.low-stocks-report.view', 'Accounting Report: Low Stocks', 'accounting', 'feature'),
  ('accounting.report.action.generate', 'Accounting Action: Generate Report', 'accounting', 'action'),
  ('accounting.report.action.export', 'Accounting Action: Export Report', 'accounting', 'action'),
  ('accounting.report.action.print', 'Accounting Action: Print Report', 'accounting', 'action'),
  ('accounting.report.action.edit-draft', 'Accounting Action: Edit Draft Workflows', 'accounting', 'action'),

  -- Purchase Order tabs/actions
  ('purchase-order.tab.deliveries', 'PO Tab: Deliveries', 'purchase-order', 'tab'),
  ('purchase-order.tab.approvals', 'PO Tab: Approvals', 'purchase-order', 'tab'),
  ('purchase-order.tab.master-data', 'PO Tab: Master Data', 'purchase-order', 'tab'),
  ('purchase-order.button.send-for-approval', 'PO Action: Send for Approval', 'purchase-order', 'action'),
  ('purchase-order.button.revert-deliveries', 'PO Action: Revert to Deliveries', 'purchase-order', 'action'),

  -- Payroll
  ('payroll.view', 'View Payroll', 'payroll', 'feature'),
  ('payroll.employee.create', 'Create Payroll Employee', 'payroll', 'action'),
  ('payroll.employee.edit', 'Edit Payroll Employee', 'payroll', 'action'),
  ('payroll.employee.delete', 'Delete Payroll Employee', 'payroll', 'action'),
  ('payroll.create', 'Create Payroll', 'payroll', 'action'),
  ('payroll.cutoff.view', 'View Payroll Cutoff', 'payroll', 'feature')
ON CONFLICT (key) DO NOTHING;

-- 14.4 Seed Role-Permission Assignments

-- Superadmin gets ALL permissions
INSERT INTO public.auth_role_permissions (role_id, permission_id)
SELECT 1, id FROM public.auth_permission_keys
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Admin gets ALL permissions
INSERT INTO public.auth_role_permissions (role_id, permission_id)
SELECT 2, id FROM public.auth_permission_keys
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Business Owner gets ALL permissions
INSERT INTO public.auth_role_permissions (role_id, permission_id)
SELECT 3, id FROM public.auth_permission_keys
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Sales role gets dashboard + projects.view + sales
INSERT INTO public.auth_role_permissions (role_id, permission_id)
SELECT 4, id FROM public.auth_permission_keys
WHERE key IN ('dashboard.view', 'projects.view', 'sales.view', 'sales.create', 'sales.edit',
              'quotation.view', 'quotation.create', 'quotation.edit', 'quotation.print')
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- User role gets dashboard + projects.view
INSERT INTO public.auth_role_permissions (role_id, permission_id)
SELECT 5, id FROM public.auth_permission_keys
WHERE key IN ('dashboard.view', 'projects.view')
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- 14.5 Seed Default Superadmin User
INSERT INTO public.tblusers (id, username, password, fullname, email, "roleId", status)
VALUES (
  1,
  'superadmin',
  '$2b$10$wJvQwQwQwQwQwQwQwQwQwOeQwQwQwQwQwQwQwQwQwQwQwQwQwQw',
  'System Superadmin',
  'superadmin@yourdomain.com',
  1,
  1
)
ON CONFLICT (id) DO NOTHING;
-- Password is bcrypt hash for 'superadmin' (change after first login!)

-- 14.6 Seed Default Account Titles
INSERT INTO public.tblaccount_titles (account_number, description, is_active)
VALUES
  ('11001', 'Cash In Bank', TRUE),
  ('14001', 'Purchases', TRUE),
  ('14010', 'Input Tax', TRUE),
  ('12001', 'Expanded Withholding Tax', TRUE),
  ('15001', 'DC-Outside Services', TRUE),
  ('15002', 'DC-Materials', TRUE),
  ('15003', 'DC-Others', TRUE)
ON CONFLICT (account_number, description) DO UPDATE
SET is_active = TRUE, updated_at = NOW();

-- 14.7 Seed Default Settings (single row)
INSERT INTO public.tblsettings (id, "businessName", cv_number_prefix, gj_number_prefix)
VALUES (1, 'BAGAMA HVAC', 'CV', 'GJ')
ON CONFLICT (id) DO NOTHING;

-- 14.8 Seed Default Branch
INSERT INTO public.tblbranches (id, "branchName", "branchAddress")
VALUES (1, 'Main Branch', 'Main Office')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- FINALIZE
-- ============================================================================

-- Fix sequences to be in sync with seeded data
SELECT setval(pg_get_serial_sequence('public.auth_permission_keys', 'id'),
  COALESCE((SELECT MAX(id) FROM public.auth_permission_keys), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('public.auth_menus', 'id'),
  COALESCE((SELECT MAX(id) FROM public.auth_menus), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('public.auth_role_permissions', 'id'),
  COALESCE((SELECT MAX(id) FROM public.auth_role_permissions), 0) + 1, false);

COMMIT;

-- ============================================================================
-- END OF FULL SCHEMA INITIALIZATION
-- ============================================================================
