
create table public.tblbranches (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "branchName" character varying null,
  "branchAddress" text null,
  constraint tblbranches_pkey primary key (id),
  constraint tblbranches_id_key unique (id)
) TABLESPACE pg_default;

create table public.tblbrands (
  id bigint generated by default as identity not null,
  "brandName" character varying null,
  prefix character varying null,
  created_at timestamp with time zone not null default now(),
  constraint tblbrands_pkey primary key (id),
  constraint tblbrands_id_key unique (id)
) TABLESPACE pg_default;

create table public.tblproducts (
  id bigint generated by default as identity not null,
  "brandId" bigint null,
  "productName" text null,
  "productType" character varying null,
  "unitTypes" text null,
  unit character varying null default 'SET'::character varying,
  created_at timestamp with time zone not null default now(),
  created_by bigint null,
  updated_at timestamp without time zone null,
  updated_by bigint null,
  deleted_at character varying null,
  deleted_by bigint null,
  constraint tblproducts_pkey primary key (id),
  constraint tblproducts_id_key unique (id),
  constraint tblproducts_productName_key unique ("productName"),
  constraint tblproducts_brandId_fkey foreign KEY ("brandId") references tblbrands (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.tblcapacity (
  id bigint generated by default as identity not null,
  "prodId" bigint null,
  capacity character varying null,
  "indoorModel" character varying null,
  "outdoorModel" character varying null,
  srp double precision null default '0'::double precision,
  "netPrice" double precision null default '0'::double precision,
  created_at timestamp with time zone not null default now(),
  "stockCount" bigint null default '0'::bigint,
  "supplierId" bigint null,
  "purchaseOrderId" bigint null,
  "purchaseOrderNo" character varying null,
  constraint tblcapacity_pkey primary key (id),
  constraint tblcapacity_prodId_fkey foreign KEY ("prodId") references tblproducts (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.tblcapacity_netprice_history (
  id bigserial not null,
  product_id bigint not null,
  capacity character varying(100) not null,
  net_price numeric(12, 2) not null,
  supplier_id bigint null,
  purchase_order_id bigint null,
  purchase_order_no character varying(100) null,
  created_by bigint null,
  created_at timestamp with time zone not null default now(),
  constraint tblcapacity_netprice_history_pkey primary key (id),
  constraint tblcapacity_netprice_history_product_id_fkey foreign KEY (product_id) references tblproducts (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.tblrbac (
  id bigint generated by default as identity not null,
  "roleName" character varying null,
  "roleMenus" text null,
  "rolePermission" text null,
  created_by bigint null,
  created_at timestamp with time zone not null default now(),
  constraint tblrbac_pkey primary key (id),
  constraint tblrbac_id_key unique (id)
) TABLESPACE pg_default;

create table public.tblusers (
  id bigint generated by default as identity not null,
  username character varying null,
  password text null,
  fullname character varying null,
  birthdate date null,
  address text null,
  email character varying null,
  contact character varying null,
  status smallint null,
  is_deleted boolean null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp without time zone null default now(),
  created_by bigint null default '1'::bigint,
  "roleId" bigint null default '1'::bigint,
  "branchId" bigint null,
  constraint tblusers_pkey primary key (id),
  constraint tblusers_id_key unique (id),
  constraint tblusers_username_key unique (username),
  constraint tblusers_branchId_fkey foreign KEY ("branchId") references tblbranches (id) on update CASCADE on delete set null,
  constraint tblusers_roleId_fkey foreign KEY ("roleId") references tblrbac (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.tblvendors (
  id uuid not null default gen_random_uuid (),
  name text not null,
  address text null,
  contact_person text null,
  contact_number text null,
  last_order_date timestamp with time zone null,
  constraint tblvendors_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tblpurchase_orders (
  id serial not null,
  po_number text GENERATED ALWAYS as (('PO-'::text || lpad((id)::text, 6, '0'::text))) STORED null,
  vendor_id uuid null,
  total_amount numeric(12, 2) null default 0,
  status text null default 'PENDING'::text,
  created_at timestamp with time zone null default now(),
  created_by bigint null,
  "branchId" bigint null,
  constraint tblpurchase_orders_pkey primary key (id),
  constraint tblpurchase_orders_branchId_fkey foreign KEY ("branchId") references tblbranches (id) on update CASCADE on delete set null,
  constraint tblpurchase_orders_created_by_fkey foreign KEY (created_by) references tblusers (id) on update CASCADE on delete set null,
  constraint tblpurchase_orders_vendor_id_fkey foreign KEY (vendor_id) references tblvendors (id)
) TABLESPACE pg_default;

create index IF not exists idx_netprice_history_lookup on public.tblcapacity_netprice_history using btree (
  product_id,
  capacity,
  supplier_id,
  purchase_order_id,
  purchase_order_no,
  id desc
) TABLESPACE pg_default;

create table public.tblcustomer (
  id uuid not null default gen_random_uuid (),
  name text not null,
  address text null,
  contact_number text null,
  email text null,
  tin_number text null,
  contact_person text null,
  constraint tblcustomer_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tblpo_payments (
  id uuid not null default gen_random_uuid (),
  po_id integer null,
  method text not null,
  payment_date character varying null,
  terms bigint null,
  "termsDueDate" character varying null,
  status character varying null,
  "paymentDate" character varying null,
  "downPayment" numeric null,
  constraint tblpo_payments_pkey primary key (id),
  constraint tblpo_payments_po_id_fkey foreign KEY (po_id) references tblpurchase_orders (id)
) TABLESPACE pg_default;

create table public.tblprocessflow (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  status character varying null,
  "nextStep" text null,
  "processedBy" bigint null,
  "stepNo" integer null,
  "stepStatus" text null,
  "actionStatus" json null,
  "actionList" json null,
  constraint tblprocessflow_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tblinstallation (
  id bigint generated by default as identity not null,
  installer_id bigint null,
  members jsonb null default '[]'::jsonb,
  "workDone" text null,
  constraint tblinstallation_pkey primary key (id),
  constraint tblinstallation_id_key unique (id)
) TABLESPACE pg_default;


create table public.tblsales_order (
  id serial not null,
  so_number text GENERATED ALWAYS as (('SO-'::text || lpad((id)::text, 6, '0'::text))) STORED null,
  customer_id uuid null,
  total_amount numeric(12, 2) null default 0,
  status text null default 'PENDING'::text,
  created_at timestamp with time zone null default now(),
  created_by bigint null,
  "branchId" bigint null,
  "scheduleDate" character varying null,
  "salesType" character varying null,
  remarks text null,
  installer text null,
  constraint tblsales_order_pkey primary key (id),
  constraint tblsales_order_branchId_fkey foreign KEY ("branchId") references tblbranches (id) on update CASCADE on delete set null,
  constraint tblsales_order_customer_id_fkey foreign KEY (customer_id) references tblcustomer (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.tblserial_numbers (
  id bigint generated by default as identity not null,
  "branchId" bigint null,
  "vendorId" uuid null,
  "purchaseId" integer null,
  "salesId" bigint null,
  "productId" bigint null,
  "capacityId" bigint null,
  "serialNumber" character varying null,
  "unitType" character varying null,
  status character varying null,
  created_at timestamp with time zone not null default now(),
  created_by bigint null,
  "customerId" uuid null,
  constraint tblserial_numbers_pkey primary key (id),
  constraint tblserial_numbers_serialNumber_key unique ("serialNumber"),
  constraint tblserial_numbers_created_by_fkey foreign KEY (created_by) references tblusers (id) on update CASCADE on delete set null,
  constraint tblserial_numbers_customerId_fkey foreign KEY ("customerId") references tblcustomer (id) on update CASCADE on delete set null,
  constraint tblserial_numbers_productId_fkey foreign KEY ("productId") references tblproducts (id) on update CASCADE on delete set null,
  constraint tblserial_numbers_purchaseId_fkey foreign KEY ("purchaseId") references tblpurchase_orders (id) on update CASCADE on delete set null,
  constraint tblserial_numbers_salesId_fkey foreign KEY ("salesId") references tblsales_order (id) on update CASCADE on delete set null,
  constraint tblserial_numbers_branchId_fkey foreign KEY ("branchId") references tblbranches (id) on update CASCADE on delete set null,
  constraint tblserial_numbers_vendorId_fkey foreign KEY ("vendorId") references tblvendors (id) on update CASCADE on delete set null,
  constraint tblserial_numbers_capacityId_fkey foreign KEY ("capacityId") references tblcapacity (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.tblsettings (
  id bigint generated by default as identity not null,
  "businessName" text null,
  "businessAddress" text null,
  "businessEmail" character varying null,
  "businessContact" character varying null,
  "businessTIN" character varying null,
  "businessOwner" character varying null,
  "businessLogo" text null,
  created_at timestamp with time zone not null default now(),
  constraint tblsettings_pkey primary key (id),
  constraint tblsettings_id_key unique (id)
) TABLESPACE pg_default;

create table public.tblso_material_items (
  id bigint generated by default as identity not null,
  material_id bigint null,
  cost double precision null,
  price double precision null,
  "excessQty" bigint null,
  "usedQty" bigint null,
  "inclusionQty" bigint null,
  sales_id integer null,
  constraint tblso_material_items_pkey primary key (id),
  constraint tblso_material_items_id_key unique (id),
  constraint tblso_material_items_sales_id_fkey foreign KEY (sales_id) references tblsales_order (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.tblso_payments (
  id uuid not null default gen_random_uuid (),
  so_id integer null,
  method text not null,
  terms bigint null,
  "termsDueDate" character varying null,
  status character varying null,
  "paymentDate" character varying null,
  "referenceNo" character varying null,
  "issuedBy" character varying null,
  "ccCharge" character varying null,
  "checkNo" character varying null,
  "bankName" character varying null,
  "bankAccount" character varying null,
  "downPayment" numeric null,
  "postDated" character varying null,
  constraint tblso_payments_pkey primary key (id),
  constraint tblso_payments_so_id_fkey foreign KEY (so_id) references tblsales_order (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.tbltransaction_product_items (
  id bigint generated by default as identity not null,
  "transType" character varying null,
  "productId" bigint null,
  "capacityId" bigint null,
  "unitPrice" double precision null,
  "sellPrice" double precision null,
  "discountPrice" double precision null,
  "unitTypesQty" jsonb null default '[]'::jsonb,
  "totalSetQty" bigint null,
  "purchaseId" integer null,
  "salesId" bigint null,
  constraint tbltransaction_product_items_pkey primary key (id),
  constraint tbltransaction_product_items_id_key unique (id),
  constraint tbltransaction_product_items_capacityId_fkey foreign KEY ("capacityId") references tblcapacity (id) on update CASCADE on delete set null,
  constraint tbltransaction_product_items_productId_fkey foreign KEY ("productId") references tblproducts (id) on update CASCADE on delete set null,
  constraint tbltransaction_product_items_purchaseId_fkey foreign KEY ("purchaseId") references tblpurchase_orders (id) on update CASCADE on delete set null,
  constraint tbltransaction_product_items_salesId_fkey foreign KEY ("salesId") references tblsales_order (id) on update CASCADE on delete set null
) TABLESPACE pg_default;