-- Quotation quote_no DB auto-generation
-- Date: 2026-03-09
--
-- Ensures quote_no is generated by DB trigger and backfills blank values.

BEGIN;

CREATE OR REPLACE FUNCTION public.tblquotation_set_quote_no()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.id IS NULL THEN
    NEW.id := nextval(pg_get_serial_sequence('public.tblquotation', 'id'));
  END IF;

  IF NEW.quote_no IS NULL OR btrim(NEW.quote_no) = '' THEN
    NEW.quote_no :=
      'QT-' ||
      to_char(COALESCE(NEW.quote_date, CURRENT_DATE), 'YYYYMMDD') ||
      '-' ||
      lpad(NEW.id::text, 6, '0');
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tblquotation_set_quote_no ON public.tblquotation;
CREATE TRIGGER trg_tblquotation_set_quote_no
BEFORE INSERT ON public.tblquotation
FOR EACH ROW EXECUTE FUNCTION public.tblquotation_set_quote_no();

UPDATE public.tblquotation
SET quote_no =
  'QT-' ||
  to_char(COALESCE(quote_date, CURRENT_DATE), 'YYYYMMDD') ||
  '-' ||
  lpad(id::text, 6, '0')
WHERE quote_no IS NULL OR btrim(quote_no) = '';

COMMIT;
