-- Combined migration script generated on 2026-03-23 05:23:38
-- Source folder: c:\laragon\www\hvac-warehouse-and-sales\backend\sql\supabase


-- ============================================================
-- BEGIN FILE: 20250308_hvac_inventory.sql
-- ============================================================


create table public.tblbranches (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "branchName" character varying null,
  "branchAddress" text null,
  constraint tblbranches_pkey primary key (id),
  constraint tblbranches_id_key unique (id)
) TABLESPACE pg_default;

create table public.tblbrands (
  id bigint generated by default as identity not null,
  "brandName" character varying null,
  prefix character varying null,
  created_at timestamp with time zone not null default now(),
  constraint tblbrands_pkey primary key (id),
  constraint tblbrands_id_key unique (id)
) TABLESPACE pg_default;

create table public.tblproducts (
  id bigint generated by default as identity not null,
  "brandId" bigint null,
  "productName" text null,
  "productType" character varying null,
  "unitTypes" text null,
  unit character varying null default 'SET'::character varying,
  created_at timestamp with time zone not null default now(),
  created_by bigint null,
  updated_at timestamp without time zone null,
  updated_by bigint null,
  deleted_at character varying null,
  deleted_by bigint null,
  constraint tblproducts_pkey primary key (id),
  constraint tblproducts_id_key unique (id),
  constraint tblproducts_productName_key unique ("productName"),
  constraint tblproducts_brandId_fkey foreign KEY ("brandId") references tblbrands (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.tblcapacity (
  id bigint generated by default as identity not null,
  "prodId" bigint null,
  capacity character varying null,
  "indoorModel" character varying null,
  "outdoorModel" character varying null,
  srp double precision null default '0'::double precision,
  "netPrice" double precision null default '0'::double precision,
  created_at timestamp with time zone not null default now(),
  "stockCount" bigint null default '0'::bigint,
  "supplierId" bigint null,
  "purchaseOrderId" bigint null,
  "purchaseOrderNo" character varying null,
  constraint tblcapacity_pkey primary key (id),
  constraint tblcapacity_prodId_fkey foreign KEY ("prodId") references tblproducts (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.tblcapacity_netprice_history (
  id bigserial not null,
  product_id bigint not null,
  capacity character varying(100) not null,
  net_price numeric(12, 2) not null,
  supplier_id bigint null,
  purchase_order_id bigint null,
  purchase_order_no character varying(100) null,
  created_by bigint null,
  created_at timestamp with time zone not null default now(),
  constraint tblcapacity_netprice_history_pkey primary key (id),
  constraint tblcapacity_netprice_history_product_id_fkey foreign KEY (product_id) references tblproducts (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.tblrbac (
  id bigint generated by default as identity not null,
  "roleName" character varying null,
  "roleMenus" text null,
  "rolePermission" text null,
  created_by bigint null,
  created_at timestamp with time zone not null default now(),
  constraint tblrbac_pkey primary key (id),
  constraint tblrbac_id_key unique (id)
) TABLESPACE pg_default;

create table public.tblusers (
  id bigint generated by default as identity not null,
  username character varying null,
  password text null,
  fullname character varying null,
  birthdate date null,
  address text null,
  email character varying null,
  contact character varying null,
  status smallint null,
  is_deleted boolean null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp without time zone null default now(),
  created_by bigint null default '1'::bigint,
  "roleId" bigint null default '1'::bigint,
  "branchId" bigint null,
  constraint tblusers_pkey primary key (id),
  constraint tblusers_id_key unique (id),
  constraint tblusers_username_key unique (username),
  constraint tblusers_branchId_fkey foreign KEY ("branchId") references tblbranches (id) on update CASCADE on delete set null,
  constraint tblusers_roleId_fkey foreign KEY ("roleId") references tblrbac (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.tblvendors (
  id uuid not null default gen_random_uuid (),
  name text not null,
  address text null,
  contact_person text null,
  contact_number text null,
  last_order_date timestamp with time zone null,
  constraint tblvendors_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tblpurchase_orders (
  id serial not null,
  po_number text GENERATED ALWAYS as (('PO-'::text || lpad((id)::text, 6, '0'::text))) STORED null,
  vendor_id uuid null,
  total_amount numeric(12, 2) null default 0,
  status text null default 'PENDING'::text,
  created_at timestamp with time zone null default now(),
  created_by bigint null,
  "branchId" bigint null,
  constraint tblpurchase_orders_pkey primary key (id),
  constraint tblpurchase_orders_branchId_fkey foreign KEY ("branchId") references tblbranches (id) on update CASCADE on delete set null,
  constraint tblpurchase_orders_created_by_fkey foreign KEY (created_by) references tblusers (id) on update CASCADE on delete set null,
  constraint tblpurchase_orders_vendor_id_fkey foreign KEY (vendor_id) references tblvendors (id)
) TABLESPACE pg_default;

create index IF not exists idx_netprice_history_lookup on public.tblcapacity_netprice_history using btree (
  product_id,
  capacity,
  supplier_id,
  purchase_order_id,
  purchase_order_no,
  id desc
) TABLESPACE pg_default;

create table public.tblcustomer (
  id uuid not null default gen_random_uuid (),
  name text not null,
  address text null,
  contact_number text null,
  email text null,
  tin_number text null,
  contact_person text null,
  constraint tblcustomer_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tblpo_payments (
  id uuid not null default gen_random_uuid (),
  po_id integer null,
  method text not null,
  payment_date character varying null,
  terms bigint null,
  "termsDueDate" character varying null,
  status character varying null,
  "paymentDate" character varying null,
  "downPayment" numeric null,
  constraint tblpo_payments_pkey primary key (id),
  constraint tblpo_payments_po_id_fkey foreign KEY (po_id) references tblpurchase_orders (id)
) TABLESPACE pg_default;

create table public.tblprocessflow (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  status character varying null,
  "nextStep" text null,
  "processedBy" bigint null,
  "stepNo" integer null,
  "stepStatus" text null,
  "actionStatus" json null,
  "actionList" json null,
  constraint tblprocessflow_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tblinstallation (
  id bigint generated by default as identity not null,
  installer_id bigint null,
  members jsonb null default '[]'::jsonb,
  "workDone" text null,
  constraint tblinstallation_pkey primary key (id),
  constraint tblinstallation_id_key unique (id)
) TABLESPACE pg_default;


create table public.tblsales_order (
  id serial not null,
  so_number text GENERATED ALWAYS as (('SO-'::text || lpad((id)::text, 6, '0'::text))) STORED null,
  customer_id uuid null,
  total_amount numeric(12, 2) null default 0,
  status text null default 'PENDING'::text,
  created_at timestamp with time zone null default now(),
  created_by bigint null,
  "branchId" bigint null,
  "scheduleDate" character varying null,
  "salesType" character varying null,
  remarks text null,
  installer text null,
  constraint tblsales_order_pkey primary key (id),
  constraint tblsales_order_branchId_fkey foreign KEY ("branchId") references tblbranches (id) on update CASCADE on delete set null,
  constraint tblsales_order_customer_id_fkey foreign KEY (customer_id) references tblcustomer (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.tblserial_numbers (
  id bigint generated by default as identity not null,
  "branchId" bigint null,
  "vendorId" uuid null,
  "purchaseId" integer null,
  "salesId" bigint null,
  "productId" bigint null,
  "capacityId" bigint null,
  "serialNumber" character varying null,
  "unitType" character varying null,
  status character varying null,
  created_at timestamp with time zone not null default now(),
  created_by bigint null,
  "customerId" uuid null,
  constraint tblserial_numbers_pkey primary key (id),
  constraint tblserial_numbers_serialNumber_key unique ("serialNumber"),
  constraint tblserial_numbers_created_by_fkey foreign KEY (created_by) references tblusers (id) on update CASCADE on delete set null,
  constraint tblserial_numbers_customerId_fkey foreign KEY ("customerId") references tblcustomer (id) on update CASCADE on delete set null,
  constraint tblserial_numbers_productId_fkey foreign KEY ("productId") references tblproducts (id) on update CASCADE on delete set null,
  constraint tblserial_numbers_purchaseId_fkey foreign KEY ("purchaseId") references tblpurchase_orders (id) on update CASCADE on delete set null,
  constraint tblserial_numbers_salesId_fkey foreign KEY ("salesId") references tblsales_order (id) on update CASCADE on delete set null,
  constraint tblserial_numbers_branchId_fkey foreign KEY ("branchId") references tblbranches (id) on update CASCADE on delete set null,
  constraint tblserial_numbers_vendorId_fkey foreign KEY ("vendorId") references tblvendors (id) on update CASCADE on delete set null,
  constraint tblserial_numbers_capacityId_fkey foreign KEY ("capacityId") references tblcapacity (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.tblsettings (
  id bigint generated by default as identity not null,
  "businessName" text null,
  "businessAddress" text null,
  "businessEmail" character varying null,
  "businessContact" character varying null,
  "businessTIN" character varying null,
  "businessOwner" character varying null,
  "businessLogo" text null,
  created_at timestamp with time zone not null default now(),
  constraint tblsettings_pkey primary key (id),
  constraint tblsettings_id_key unique (id)
) TABLESPACE pg_default;

create table public.tblso_material_items (
  id bigint generated by default as identity not null,
  material_id bigint null,
  cost double precision null,
  price double precision null,
  "excessQty" bigint null,
  "usedQty" bigint null,
  "inclusionQty" bigint null,
  sales_id integer null,
  constraint tblso_material_items_pkey primary key (id),
  constraint tblso_material_items_id_key unique (id),
  constraint tblso_material_items_sales_id_fkey foreign KEY (sales_id) references tblsales_order (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.tblso_payments (
  id uuid not null default gen_random_uuid (),
  so_id integer null,
  method text not null,
  terms bigint null,
  "termsDueDate" character varying null,
  status character varying null,
  "paymentDate" character varying null,
  "referenceNo" character varying null,
  "issuedBy" character varying null,
  "ccCharge" character varying null,
  "checkNo" character varying null,
  "bankName" character varying null,
  "bankAccount" character varying null,
  "downPayment" numeric null,
  "postDated" character varying null,
  constraint tblso_payments_pkey primary key (id),
  constraint tblso_payments_so_id_fkey foreign KEY (so_id) references tblsales_order (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.tbltransaction_product_items (
  id bigint generated by default as identity not null,
  "transType" character varying null,
  "productId" bigint null,
  "capacityId" bigint null,
  "unitPrice" double precision null,
  "sellPrice" double precision null,
  "discountPrice" double precision null,
  "unitTypesQty" jsonb null default '[]'::jsonb,
  "totalSetQty" bigint null,
  "purchaseId" integer null,
  "salesId" bigint null,
  constraint tbltransaction_product_items_pkey primary key (id),
  constraint tbltransaction_product_items_id_key unique (id),
  constraint tbltransaction_product_items_capacityId_fkey foreign KEY ("capacityId") references tblcapacity (id) on update CASCADE on delete set null,
  constraint tbltransaction_product_items_productId_fkey foreign KEY ("productId") references tblproducts (id) on update CASCADE on delete set null,
  constraint tbltransaction_product_items_purchaseId_fkey foreign KEY ("purchaseId") references tblpurchase_orders (id) on update CASCADE on delete set null,
  constraint tbltransaction_product_items_salesId_fkey foreign KEY ("salesId") references tblsales_order (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

-- END FILE: 20250308_hvac_inventory.sql


-- ============================================================
-- BEGIN FILE: 20260307_rbac_normalization.sql
-- ============================================================

-- RBAC normalization migration for Supabase PostgreSQL
-- Date: 2026-03-07
--
-- Goal:
-- 1) Keep existing tables (`tblrbac`, `tblusers`) as-is for backward compatibility.
-- 2) Introduce normalized permission model for module/menu/tab/action-level control.
-- 3) Support per-user permission overrides (allow/deny).
--
-- Safe to run multiple times (idempotent patterns used where possible).

BEGIN;

-- 1) Normalized permission dictionary
CREATE TABLE IF NOT EXISTS public.auth_permission_keys (
  id BIGSERIAL PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  module TEXT NOT NULL,
  scope TEXT NOT NULL DEFAULT 'feature', -- feature | menu | tab | action
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT auth_permission_keys_scope_check CHECK (scope IN ('feature', 'menu', 'tab', 'action'))
);

-- 2) Role -> permission mapping
CREATE TABLE IF NOT EXISTS public.auth_role_permissions (
  id BIGSERIAL PRIMARY KEY,
  role_id BIGINT NOT NULL REFERENCES public.tblrbac(id) ON DELETE CASCADE,
  permission_id BIGINT NOT NULL REFERENCES public.auth_permission_keys(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(role_id, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_role_permissions_role_id
  ON public.auth_role_permissions(role_id);

CREATE INDEX IF NOT EXISTS idx_auth_role_permissions_permission_id
  ON public.auth_role_permissions(permission_id);

-- 3) User-level overrides (allow/deny)
CREATE TABLE IF NOT EXISTS public.auth_user_permission_overrides (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.tblusers(id) ON DELETE CASCADE,
  permission_id BIGINT NOT NULL REFERENCES public.auth_permission_keys(id) ON DELETE CASCADE,
  effect TEXT NOT NULL, -- allow | deny
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT auth_user_permission_overrides_effect_check CHECK (effect IN ('allow', 'deny')),
  UNIQUE(user_id, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_user_permission_overrides_user_id
  ON public.auth_user_permission_overrides(user_id);

CREATE INDEX IF NOT EXISTS idx_auth_user_permission_overrides_permission_id
  ON public.auth_user_permission_overrides(permission_id);

-- 4) Optional assignment table for explicit user roles (future-proof).
-- This is useful if you later move away from mixed-case dynamic role columns in tblusers.
CREATE TABLE IF NOT EXISTS public.auth_user_roles (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.tblusers(id) ON DELETE CASCADE,
  role_id BIGINT NOT NULL REFERENCES public.tblrbac(id) ON DELETE CASCADE,
  is_primary BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_user_roles_user_id
  ON public.auth_user_roles(user_id);

CREATE INDEX IF NOT EXISTS idx_auth_user_roles_role_id
  ON public.auth_user_roles(role_id);

-- 5) Keep updated_at timestamps fresh.
CREATE OR REPLACE FUNCTION public.set_current_timestamp_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_auth_permission_keys_updated_at ON public.auth_permission_keys;
CREATE TRIGGER trg_auth_permission_keys_updated_at
BEFORE UPDATE ON public.auth_permission_keys
FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();

DROP TRIGGER IF EXISTS trg_auth_user_permission_overrides_updated_at ON public.auth_user_permission_overrides;
CREATE TRIGGER trg_auth_user_permission_overrides_updated_at
BEFORE UPDATE ON public.auth_user_permission_overrides
FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();

-- 6) Seed common app permissions (SO/PO tabs included).
-- Use this as your canonical list going forward.
INSERT INTO public.auth_permission_keys(key, label, module, scope)
VALUES
  ('user-management.view', 'View User Management', 'user-management', 'feature'),
  ('user-management.create', 'Create User', 'user-management', 'action'),
  ('user-management.edit', 'Edit User', 'user-management', 'action'),
  ('user-management.delete', 'Delete User', 'user-management', 'action'),

  ('sales-order.view', 'View Sales Orders', 'sales-order', 'feature'),
  ('sales-order.create', 'Create Sales Order', 'sales-order', 'action'),
  ('sales-order.edit', 'Edit Sales Order', 'sales-order', 'action'),
  ('sales-order.remit', 'Remit Sales', 'sales-order', 'action'),
  ('sales-order.print-dr', 'Print Delivery Receipt', 'sales-order', 'action'),
  ('sales-order.tab.schedules', 'SO Tab: Schedules', 'sales-order', 'tab'),
  ('sales-order.tab.services', 'SO Tab: Services', 'sales-order', 'tab'),
  ('sales-order.tab.projects', 'SO Tab: Projects', 'sales-order', 'tab'),
  ('sales-order.tab.distribution', 'SO Tab: Distribution', 'sales-order', 'tab'),
  ('sales-order.tab.sales-receivable', 'SO Tab: Sales Receivable', 'sales-order', 'tab'),
  ('sales-order.tab.remitted-sales', 'SO Tab: Remitted Sales', 'sales-order', 'tab'),

  ('purchase-order.view', 'View Purchase Orders', 'purchase-order', 'feature'),
  ('purchase-order.create', 'Create Purchase Order', 'purchase-order', 'action'),
  ('purchase-order.edit', 'Edit Purchase Order', 'purchase-order', 'action'),
  ('purchase-order.approve', 'Approve Purchase Order', 'purchase-order', 'action'),
  ('purchase-order.tab.local', 'PO Tab: Local', 'purchase-order', 'tab'),
  ('purchase-order.tab.imported', 'PO Tab: Imported', 'purchase-order', 'tab'),

  ('customers.view', 'View Customers', 'customers', 'feature'),
  ('customers.create', 'Create Customer', 'customers', 'action'),
  ('customers.edit', 'Edit Customer', 'customers', 'action'),
  ('customers.delete', 'Delete Customer', 'customers', 'action')
ON CONFLICT (key) DO NOTHING;

-- 7) Backfill role->permission links from legacy CSV strings in tblrbac.
--    Legacy fields expected: roleMenus, rolePermission (or lowercase variants).
WITH role_tokens AS (
  SELECT
    r.id AS role_id,
    lower(trim(token)) AS token,
    'menu'::text AS source
  FROM public.tblrbac r
  CROSS JOIN LATERAL regexp_split_to_table(
    COALESCE(to_jsonb(r)->>'roleMenus', to_jsonb(r)->>'rolemenus', ''),
    ','
  ) AS token
  WHERE trim(token) <> ''

  UNION ALL

  SELECT
    r.id AS role_id,
    lower(trim(token)) AS token,
    'permission'::text AS source
  FROM public.tblrbac r
  CROSS JOIN LATERAL regexp_split_to_table(
    COALESCE(to_jsonb(r)->>'rolePermission', to_jsonb(r)->>'rolepermission', ''),
    ','
  ) AS token
  WHERE trim(token) <> ''
), normalized_tokens AS (
  SELECT
    role_id,
    source,
    regexp_replace(token, '[^a-z0-9]+', '-', 'g') AS slug
  FROM role_tokens
), ensured_permissions AS (
  INSERT INTO public.auth_permission_keys(key, label, module, scope)
  SELECT DISTINCT
    CASE
      WHEN source = 'menu' THEN CONCAT('legacy.menu.', slug)
      ELSE CONCAT('legacy.permission.', slug)
    END AS key,
    CONCAT('Legacy ', initcap(source), ': ', slug) AS label,
    'legacy' AS module,
    CASE
      WHEN source = 'menu' THEN 'menu'
      ELSE 'action'
    END AS scope
  FROM normalized_tokens
  WHERE slug <> ''
  ON CONFLICT (key) DO NOTHING
  RETURNING id, key
)
INSERT INTO public.auth_role_permissions(role_id, permission_id)
SELECT DISTINCT
  nt.role_id,
  pk.id AS permission_id
FROM normalized_tokens nt
JOIN public.auth_permission_keys pk
  ON pk.key = CASE
    WHEN nt.source = 'menu' THEN CONCAT('legacy.menu.', nt.slug)
    ELSE CONCAT('legacy.permission.', nt.slug)
  END
WHERE nt.slug <> ''
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- 8) Backfill auth_user_roles from tblusers role id (mixed naming support).
INSERT INTO public.auth_user_roles(user_id, role_id, is_primary)
SELECT DISTINCT
  u.id AS user_id,
  NULLIF(
    COALESCE(
      to_jsonb(u)->>'roleId',
      to_jsonb(u)->>'roleid',
      to_jsonb(u)->>'role_id'
    ),
    ''
  )::bigint AS role_id,
  TRUE AS is_primary
FROM public.tblusers u
WHERE NULLIF(
  COALESCE(
    to_jsonb(u)->>'roleId',
    to_jsonb(u)->>'roleid',
    to_jsonb(u)->>'role_id'
  ),
  ''
) IS NOT NULL
ON CONFLICT (user_id, role_id) DO NOTHING;

-- 9) Resolved effective permissions view.
--    Rule: user deny override > user allow override > role grant.
CREATE OR REPLACE VIEW public.v_auth_user_effective_permissions AS
WITH role_grants AS (
  SELECT
    ur.user_id,
    rp.permission_id,
    TRUE AS granted_by_role
  FROM public.auth_user_roles ur
  JOIN public.auth_role_permissions rp
    ON rp.role_id = ur.role_id
), user_overrides AS (
  SELECT
    user_id,
    permission_id,
    MAX(CASE WHEN effect = 'allow' THEN 1 ELSE 0 END) AS has_allow,
    MAX(CASE WHEN effect = 'deny' THEN 1 ELSE 0 END) AS has_deny
  FROM public.auth_user_permission_overrides
  GROUP BY user_id, permission_id
), all_candidates AS (
  SELECT user_id, permission_id FROM role_grants
  UNION
  SELECT user_id, permission_id FROM user_overrides
)
SELECT
  c.user_id,
  pk.key AS permission_key,
  pk.label AS permission_label,
  pk.module,
  pk.scope,
  CASE
    WHEN COALESCE(uo.has_deny, 0) = 1 THEN FALSE
    WHEN COALESCE(uo.has_allow, 0) = 1 THEN TRUE
    WHEN rg.granted_by_role IS TRUE THEN TRUE
    ELSE FALSE
  END AS is_allowed,
  CASE
    WHEN COALESCE(uo.has_deny, 0) = 1 THEN 'user-deny'
    WHEN COALESCE(uo.has_allow, 0) = 1 THEN 'user-allow'
    WHEN rg.granted_by_role IS TRUE THEN 'role'
    ELSE 'none'
  END AS source
FROM all_candidates c
JOIN public.auth_permission_keys pk
  ON pk.id = c.permission_id
LEFT JOIN role_grants rg
  ON rg.user_id = c.user_id AND rg.permission_id = c.permission_id
LEFT JOIN user_overrides uo
  ON uo.user_id = c.user_id AND uo.permission_id = c.permission_id;

COMMIT;

-- END FILE: 20260307_rbac_normalization.sql


-- ============================================================
-- BEGIN FILE: 20260308_quotation_feature.sql
-- ============================================================

-- Quotation feature migration
-- Date: 2026-03-08
--
-- Adds normalized quotation tables and permission keys.
-- Table names follow legacy convention and start with "tbl".

BEGIN;

CREATE TABLE IF NOT EXISTS public.tblquotation (
  id BIGSERIAL PRIMARY KEY,
  quote_no TEXT NOT NULL UNIQUE,
  quote_date DATE NOT NULL DEFAULT CURRENT_DATE,

  -- Normalized FK to customer; keep denormalized snapshot fields for immutable print preview.
  customer_id uuid REFERENCES public.tblcustomer(id) ON DELETE SET NULL,
  customer_name TEXT,
  customer_address TEXT,
  customer_contact_person TEXT,
  customer_contact_number TEXT,
  customer_email TEXT,
  customer_tin_number TEXT,

  total_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'draft',
  remarks TEXT,

  -- Track downstream conversion to Sales Order.
  converted_sales_id BIGINT REFERENCES public.tblsales_order(id) ON DELETE SET NULL,

  -- Audit and multi-branch friendliness.
  created_by BIGINT REFERENCES public.tblusers(id) ON DELETE SET NULL,
  branch_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT tblquotation_status_check
    CHECK (LOWER(status) IN ('draft', 'finalized', 'converted', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_tblquotation_customer_id ON public.tblquotation(customer_id);
CREATE INDEX IF NOT EXISTS idx_tblquotation_status ON public.tblquotation(status);
CREATE INDEX IF NOT EXISTS idx_tblquotation_quote_date ON public.tblquotation(quote_date);
CREATE INDEX IF NOT EXISTS idx_tblquotation_created_at ON public.tblquotation(created_at DESC);

CREATE OR REPLACE FUNCTION public.tblquotation_set_quote_no()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.id IS NULL THEN
    NEW.id := nextval(pg_get_serial_sequence('public.tblquotation', 'id'));
  END IF;

  IF NEW.quote_no IS NULL OR btrim(NEW.quote_no) = '' THEN
    NEW.quote_no :=
      'QT-' ||
      to_char(COALESCE(NEW.quote_date, CURRENT_DATE), 'YYYYMMDD') ||
      '-' ||
      lpad(NEW.id::text, 6, '0');
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tblquotation_set_quote_no ON public.tblquotation;
CREATE TRIGGER trg_tblquotation_set_quote_no
BEFORE INSERT ON public.tblquotation
FOR EACH ROW EXECUTE FUNCTION public.tblquotation_set_quote_no();

CREATE TABLE IF NOT EXISTS public.tblquotation_items (
  id BIGSERIAL PRIMARY KEY,

  -- Normalized FK to quotation header.
  quotation_id BIGINT NOT NULL REFERENCES public.tblquotation(id) ON DELETE CASCADE,

  -- Normalized product-capacity references used by conversion to SO.
  product_id BIGINT REFERENCES public.tblproducts(id) ON DELETE SET NULL,
  capacity_id BIGINT REFERENCES public.tblcapacity(id) ON DELETE SET NULL,

  unit_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  sell_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  discount_price NUMERIC(14, 2) NOT NULL DEFAULT 0,

  -- Keep same shape as existing SO/PO item handling.
  unit_types_qty JSONB NOT NULL DEFAULT '[]'::jsonb,
  total_set_qty INTEGER NOT NULL DEFAULT 0,
  line_total NUMERIC(14, 2) NOT NULL DEFAULT 0,
  remarks TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tblquotation_items_quotation_id
  ON public.tblquotation_items(quotation_id);
CREATE INDEX IF NOT EXISTS idx_tblquotation_items_product_id
  ON public.tblquotation_items(product_id);
CREATE INDEX IF NOT EXISTS idx_tblquotation_items_capacity_id
  ON public.tblquotation_items(capacity_id);

-- Reuse existing timestamp trigger function from RBAC migration when available.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_proc
    WHERE proname = 'set_current_timestamp_updated_at'
      AND pg_function_is_visible(oid)
  ) THEN
    DROP TRIGGER IF EXISTS trg_tblquotation_updated_at ON public.tblquotation;
    CREATE TRIGGER trg_tblquotation_updated_at
    BEFORE UPDATE ON public.tblquotation
    FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();

    DROP TRIGGER IF EXISTS trg_tblquotation_items_updated_at ON public.tblquotation_items;
    CREATE TRIGGER trg_tblquotation_items_updated_at
    BEFORE UPDATE ON public.tblquotation_items
    FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();
  END IF;
END $$;

-- Seed normalized permission keys for quotation feature.
INSERT INTO public.auth_permission_keys(key, label, module, scope)
VALUES
  ('quotation.view', 'View Quotations', 'quotation', 'feature'),
  ('quotation.create', 'Create Quotation', 'quotation', 'action'),
  ('quotation.edit', 'Edit Quotation', 'quotation', 'action'),
  ('quotation.finalize', 'Finalize Quotation', 'quotation', 'action'),
  ('quotation.convert', 'Convert Quotation to SO', 'quotation', 'action'),
  ('quotation.print', 'Print Quotation', 'quotation', 'action'),
  ('legacy.menu.quotation', 'Legacy Menu: quotation', 'legacy', 'menu')
ON CONFLICT (key) DO NOTHING;

-- Bridge legacy roleMenus token (quotation) into normalized role-permission mapping.
INSERT INTO public.auth_role_permissions(role_id, permission_id)
SELECT DISTINCT
  r.id AS role_id,
  pk.id AS permission_id
FROM public.tblrbac r
INNER JOIN public.auth_permission_keys pk
  ON pk.key = 'legacy.menu.quotation'
WHERE EXISTS (
  SELECT 1
  FROM regexp_split_to_table(
    COALESCE(to_jsonb(r)->>'roleMenus', to_jsonb(r)->>'rolemenus', ''),
    ','
  ) AS token
  WHERE lower(trim(token)) = 'quotation'
)
ON CONFLICT (role_id, permission_id) DO NOTHING;

COMMIT;

-- END FILE: 20260308_quotation_feature.sql


-- ============================================================
-- BEGIN FILE: 20260309_material_inventory_ledger.sql
-- ============================================================

CREATE TABLE IF NOT EXISTS tblmaterial_items (
  id BIGSERIAL PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'pcs',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tblproduct_capacity_material_map (
  id BIGSERIAL PRIMARY KEY,
  product_id BIGINT NOT NULL,
  capacity_id BIGINT NOT NULL,
  material_id BIGINT NOT NULL REFERENCES tblmaterial_items(id),
  qty_per_set NUMERIC(14, 4) NOT NULL DEFAULT 1,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(product_id, capacity_id, material_id)
);

CREATE TABLE IF NOT EXISTS tblmaterial_stock_balance (
  id BIGSERIAL PRIMARY KEY,
  material_id BIGINT NOT NULL REFERENCES tblmaterial_items(id),
  on_hand NUMERIC(14, 2) NOT NULL DEFAULT 0,
  reserved NUMERIC(14, 2) NOT NULL DEFAULT 0,
  available NUMERIC(14, 2) GENERATED ALWAYS AS (on_hand - reserved) STORED,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(material_id)
);

CREATE TABLE IF NOT EXISTS tblmaterial_stock_movement (
  id BIGSERIAL PRIMARY KEY,
  material_id BIGINT NOT NULL REFERENCES tblmaterial_items(id),
  movement_type TEXT NOT NULL CHECK (movement_type IN ('IN', 'OUT', 'RESERVE', 'RELEASE', 'RETURN', 'ADJUST')),
  qty NUMERIC(14, 2) NOT NULL CHECK (qty > 0),
  source_type TEXT NOT NULL CHECK (source_type IN ('PO', 'SO', 'MANUAL')),
  source_id BIGINT NOT NULL,
  source_line_key TEXT NOT NULL,
  status_snapshot TEXT,
  remarks TEXT,
  created_by BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(source_type, source_id, movement_type, source_line_key)
);

CREATE INDEX IF NOT EXISTS idx_material_stock_movement_source
  ON tblmaterial_stock_movement(source_type, source_id);

CREATE INDEX IF NOT EXISTS idx_material_stock_movement_material
  ON tblmaterial_stock_movement(material_id, created_at DESC);

-- END FILE: 20260309_material_inventory_ledger.sql


-- ============================================================
-- BEGIN FILE: 20260309_quotation_quote_no_auto.sql
-- ============================================================

-- Quotation quote_no DB auto-generation
-- Date: 2026-03-09
--
-- Ensures quote_no is generated by DB trigger and backfills blank values.

BEGIN;

CREATE OR REPLACE FUNCTION public.tblquotation_set_quote_no()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.id IS NULL THEN
    NEW.id := nextval(pg_get_serial_sequence('public.tblquotation', 'id'));
  END IF;

  IF NEW.quote_no IS NULL OR btrim(NEW.quote_no) = '' THEN
    NEW.quote_no :=
      'QT-' ||
      to_char(COALESCE(NEW.quote_date, CURRENT_DATE), 'YYYYMMDD') ||
      '-' ||
      lpad(NEW.id::text, 6, '0');
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tblquotation_set_quote_no ON public.tblquotation;
CREATE TRIGGER trg_tblquotation_set_quote_no
BEFORE INSERT ON public.tblquotation
FOR EACH ROW EXECUTE FUNCTION public.tblquotation_set_quote_no();

UPDATE public.tblquotation
SET quote_no =
  'QT-' ||
  to_char(COALESCE(quote_date, CURRENT_DATE), 'YYYYMMDD') ||
  '-' ||
  lpad(id::text, 6, '0')
WHERE quote_no IS NULL OR btrim(quote_no) = '';

COMMIT;

-- END FILE: 20260309_quotation_quote_no_auto.sql


-- ============================================================
-- BEGIN FILE: 20260310_material_inventory_enhancement.sql
-- ============================================================

-- =====================================================
-- HVAC Management System - Material Inventory & Enhancements
-- Migration Date: 2026-03-10
-- Author: Senior Full-Stack Developer
-- Description: Comprehensive database schema for Material Inventory,
--              Sales Order Enhancements, Customer Management, and Accounting
-- =====================================================

-- =====================================================
-- SECTION 1: BRAND TYPE ENHANCEMENT
-- Purpose: Add type column to differentiate AC Units (ACU) from Materials (MAT)
-- =====================================================

-- Add type column to tblbrands if not exists
-- ACU = AC Unit brands, MAT = Material brands
ALTER TABLE public.tblbrands 
ADD COLUMN IF NOT EXISTS type VARCHAR(10) DEFAULT 'ACU' CHECK (type IN ('ACU', 'MAT'));

-- Add index for faster filtering by type
CREATE INDEX IF NOT EXISTS idx_tblbrands_type ON public.tblbrands(type);

-- Update existing brands to ACU (default for existing AC unit brands)
UPDATE public.tblbrands SET type = 'ACU' WHERE type IS NULL;

COMMENT ON COLUMN public.tblbrands.type IS 'Brand type: ACU for AC Units, MAT for Materials';


-- =====================================================
-- SECTION 2: MATERIAL PRODUCTS TABLE
-- Purpose: Store material products separate from AC units
-- =====================================================

-- Create materials table for material inventory management
CREATE TABLE IF NOT EXISTS public.tblmaterials (
  id BIGSERIAL PRIMARY KEY,
  brand_id BIGINT NULL REFERENCES public.tblbrands(id) ON UPDATE CASCADE ON DELETE SET NULL,
  material_name TEXT NOT NULL,
  material_code VARCHAR(50) UNIQUE, -- SKU or material code
  description TEXT,
  unit VARCHAR(20) DEFAULT 'PCS', -- PCS, METERS, LITERS, KG, etc.
  unit_price NUMERIC(12, 2) DEFAULT 0, -- Cost price
  sell_price NUMERIC(12, 2) DEFAULT 0, -- Selling price
  on_hand_stock BIGINT DEFAULT 0, -- Current stock quantity
  reorder_level BIGINT DEFAULT 0, -- Minimum stock level for reorder alert
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL,
  updated_at TIMESTAMPTZ,
  updated_by BIGINT REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL,
  deleted_at TIMESTAMPTZ,
  deleted_by BIGINT REFERENCES public.tblusers(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT tblmaterials_material_name_key UNIQUE (material_name)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_tblmaterials_brand_id ON public.tblmaterials(brand_id);
CREATE INDEX IF NOT EXISTS idx_tblmaterials_deleted_at ON public.tblmaterials(deleted_at);
CREATE INDEX IF NOT EXISTS idx_tblmaterials_on_hand_stock ON public.tblmaterials(on_hand_stock);

COMMENT ON TABLE public.tblmaterials IS 'Material products inventory (pipes, wires, accessories, etc.)';
COMMENT ON COLUMN public.tblmaterials.on_hand_stock IS 'Current available stock quantity';
COMMENT ON COLUMN public.tblmaterials.reorder_level IS 'Alert threshold for low stock';


-- =====================================================
-- SECTION 3: MATERIAL PRICE HISTORY
-- Purpose: Track material price changes over time
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tblmaterial_price_history (
  id BIGSERIAL PRIMARY KEY,
  material_id BIGINT NOT NULL REFERENCES public.tblmaterials(id) ON DELETE CASCADE,
  unit_price NUMERIC(12, 2) NOT NULL,
  sell_price NUMERIC(12, 2) NOT NULL,
  supplier_id UUID REFERENCES public.tblvendors(id),
  purchase_order_id INTEGER REFERENCES public.tblpurchase_orders(id),
  purchase_order_no VARCHAR(100),
  created_by BIGINT REFERENCES public.tblusers(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_material_price_history_lookup 
ON public.tblmaterial_price_history(material_id, id DESC);

COMMENT ON TABLE public.tblmaterial_price_history IS 'Historical tracking of material price changes';


-- =====================================================
-- SECTION 4: PURCHASE ORDER TYPE ENHANCEMENT
-- Purpose: Differentiate between AC Unit PO and Material PO
-- =====================================================

-- Add po_type column to purchase orders
ALTER TABLE public.tblpurchase_orders 
ADD COLUMN IF NOT EXISTS po_type VARCHAR(20) DEFAULT 'ACU' CHECK (po_type IN ('ACU', 'MATERIAL'));

-- Add index for filtering by PO type
CREATE INDEX IF NOT EXISTS idx_tblpurchase_orders_po_type ON public.tblpurchase_orders(po_type);

COMMENT ON COLUMN public.tblpurchase_orders.po_type IS 'Purchase order type: ACU for AC Units, MATERIAL for materials';


-- =====================================================
-- SECTION 5: MATERIAL TRANSACTION ITEMS
-- Purpose: Track material items in purchase orders and sales orders
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tbltransaction_material_items (
  id BIGSERIAL PRIMARY KEY,
  trans_type VARCHAR(20) NOT NULL CHECK (trans_type IN ('purchase', 'sales')), -- purchase or sales
  material_id BIGINT NOT NULL REFERENCES public.tblmaterials(id) ON UPDATE CASCADE ON DELETE CASCADE,
  quantity BIGINT NOT NULL DEFAULT 0,
  unit_price NUMERIC(12, 2) DEFAULT 0, -- Cost price at time of transaction
  sell_price NUMERIC(12, 2) DEFAULT 0, -- Selling price at time of transaction
  discount_price NUMERIC(12, 2) DEFAULT 0,
  purchase_id INTEGER REFERENCES public.tblpurchase_orders(id) ON UPDATE CASCADE ON DELETE CASCADE,
  sales_id INTEGER REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_transaction_material_purchase ON public.tbltransaction_material_items(purchase_id);
CREATE INDEX IF NOT EXISTS idx_transaction_material_sales ON public.tbltransaction_material_items(sales_id);
CREATE INDEX IF NOT EXISTS idx_transaction_material_material_id ON public.tbltransaction_material_items(material_id);

COMMENT ON TABLE public.tbltransaction_material_items IS 'Material items in purchase and sales transactions';


-- =====================================================
-- SECTION 6: SALES ORDER ENHANCEMENTS - PROJECT DETAILS
-- Purpose: Store project-specific information for project sales type
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tblproject_details (
  id BIGSERIAL PRIMARY KEY,
  sales_id INTEGER NOT NULL REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  project_name TEXT NOT NULL,
  project_code VARCHAR(50) UNIQUE,
  project_location TEXT,
  project_start_date DATE,
  project_end_date DATE,
  project_manager TEXT,
  project_status VARCHAR(20) DEFAULT 'ongoing' CHECK (project_status IN ('planning', 'ongoing', 'completed', 'cancelled')),
  project_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT tblproject_details_sales_id_key UNIQUE (sales_id)
);

CREATE INDEX IF NOT EXISTS idx_project_details_sales_id ON public.tblproject_details(sales_id);
CREATE INDEX IF NOT EXISTS idx_project_details_status ON public.tblproject_details(project_status);

COMMENT ON TABLE public.tblproject_details IS 'Project-specific details for project sales type';


-- =====================================================
-- SECTION 7: SERVICE DETAILS TABLE
-- Purpose: Store service information for service-related sales
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tblservice_details (
  id BIGSERIAL PRIMARY KEY,
  sales_id INTEGER NOT NULL REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  service_name TEXT NOT NULL,
  service_description TEXT,
  service_type VARCHAR(50), -- Installation, Maintenance, Repair, etc.
  technician_assigned TEXT,
  service_date DATE,
  service_duration_hours NUMERIC(5, 2),
  service_cost NUMERIC(12, 2) DEFAULT 0,
  parts_cost NUMERIC(12, 2) DEFAULT 0,
  labor_cost NUMERIC(12, 2) DEFAULT 0,
  service_status VARCHAR(20) DEFAULT 'scheduled' CHECK (service_status IN ('scheduled', 'in_progress', 'completed', 'cancelled')),
  service_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_service_details_sales_id ON public.tblservice_details(sales_id);
CREATE INDEX IF NOT EXISTS idx_service_details_status ON public.tblservice_details(service_status);
CREATE INDEX IF NOT EXISTS idx_service_details_date ON public.tblservice_details(service_date);

COMMENT ON TABLE public.tblservice_details IS 'Service details for sales orders with service component';


-- =====================================================
-- SECTION 8: CONCERN DETAILS TABLE
-- Purpose: Store customer concerns and issues
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tblconcern_details (
  id BIGSERIAL PRIMARY KEY,
  sales_id INTEGER REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  customer_id UUID REFERENCES public.tblcustomer(id) ON UPDATE CASCADE ON DELETE CASCADE,
  concern_type VARCHAR(50), -- Complaint, Inquiry, Technical Issue, etc.
  concern_subject TEXT NOT NULL,
  concern_description TEXT NOT NULL,
  concern_status VARCHAR(20) DEFAULT 'open' CHECK (concern_status IN ('open', 'in_progress', 'resolved', 'closed')),
  priority VARCHAR(20) DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  assigned_to BIGINT REFERENCES public.tblusers(id),
  resolution_notes TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_concern_details_sales_id ON public.tblconcern_details(sales_id);
CREATE INDEX IF NOT EXISTS idx_concern_details_customer_id ON public.tblconcern_details(customer_id);
CREATE INDEX IF NOT EXISTS idx_concern_details_status ON public.tblconcern_details(concern_status);

COMMENT ON TABLE public.tblconcern_details IS 'Customer concerns, complaints, and issues tracking';


-- =====================================================
-- SECTION 9: TRANSFER/DISTRIBUTION DETAILS
-- Purpose: Track branch-to-branch transfers
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tbltransfer_details (
  id BIGSERIAL PRIMARY KEY,
  sales_id INTEGER NOT NULL REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  from_branch_id BIGINT NOT NULL REFERENCES public.tblbranches(id),
  to_branch_id BIGINT NOT NULL REFERENCES public.tblbranches(id),
  transfer_date DATE,
  expected_delivery_date DATE,
  actual_delivery_date DATE,
  transfer_status VARCHAR(20) DEFAULT 'pending' CHECK (transfer_status IN ('pending', 'in_transit', 'delivered', 'acknowledged', 'cancelled')),
  sent_by BIGINT REFERENCES public.tblusers(id),
  received_by BIGINT REFERENCES public.tblusers(id),
  acknowledged_by BIGINT REFERENCES public.tblusers(id),
  acknowledged_at TIMESTAMPTZ,
  transfer_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT tbltr ansfer_details_sales_id_key UNIQUE (sales_id)
);

CREATE INDEX IF NOT EXISTS idx_transfer_details_from_branch ON public.tbltransfer_details(from_branch_id);
CREATE INDEX IF NOT EXISTS idx_transfer_details_to_branch ON public.tbltransfer_details(to_branch_id);
CREATE INDEX IF NOT EXISTS idx_transfer_details_status ON public.tbltransfer_details(transfer_status);

COMMENT ON TABLE public.tbltransfer_details IS 'Branch-to-branch transfer/distribution tracking';


-- =====================================================
-- SECTION 10: EXPENSE DETAILS FOR TRANSFERS
-- Purpose: Track expenses related to transfers
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tblexpense_details (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sales_id INTEGER REFERENCES public.tblsales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
  transfer_id BIGINT REFERENCES public.tbltransfer_details(id) ON UPDATE CASCADE ON DELETE CASCADE,
  expense_type VARCHAR(50) NOT NULL, -- Transportation, Handling, Insurance, etc.
  expense_description TEXT,
  amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  expense_date DATE,
  paid_to TEXT,
  payment_method VARCHAR(50),
  reference_no VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_expense_details_sales_id ON public.tblexpense_details(sales_id);
CREATE INDEX IF NOT EXISTS idx_expense_details_transfer_id ON public.tblexpense_details(transfer_id);

COMMENT ON TABLE public.tblexpense_details IS 'Expense tracking for transfers and distributions';


-- =====================================================
-- SECTION 11: CUSTOMER ENHANCEMENTS - SUB-DEALER FLAG
-- Purpose: Differentiate regular customers from sub-dealers
-- =====================================================

ALTER TABLE public.tblcustomer 
ADD COLUMN IF NOT EXISTS customer_type VARCHAR(20) DEFAULT 'regular' CHECK (customer_type IN ('regular', 'sub_dealer'));

ALTER TABLE public.tblcustomer 
ADD COLUMN IF NOT EXISTS credit_limit NUMERIC(12, 2) DEFAULT 0;

ALTER TABLE public.tblcustomer 
ADD COLUMN IF NOT EXISTS current_balance NUMERIC(12, 2) DEFAULT 0;

ALTER TABLE public.tblcustomer 
ADD COLUMN IF NOT EXISTS payment_terms INTEGER DEFAULT 0; -- Days

ALTER TABLE public.tblcustomer 
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public.tblcustomer 
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_tblcustomer_type ON public.tblcustomer(customer_type);

COMMENT ON COLUMN public.tblcustomer.customer_type IS 'Customer type: regular or sub_dealer';
COMMENT ON COLUMN public.tblcustomer.credit_limit IS 'Maximum credit allowed for sub-dealers';
COMMENT ON COLUMN public.tblcustomer.current_balance IS 'Current outstanding balance';


-- =====================================================
-- SECTION 12: CUSTOMER PAYMENT HISTORY
-- Purpose: Track all customer payments
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tblcustomer_payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL REFERENCES public.tblcustomer(id) ON UPDATE CASCADE ON DELETE CASCADE,
  sales_id INTEGER REFERENCES public.tblsales_order(id),
  payment_amount NUMERIC(12, 2) NOT NULL,
  payment_date DATE NOT NULL,
  payment_method VARCHAR(50),
  reference_no VARCHAR(100),
  payment_notes TEXT,
  applied_to_balance NUMERIC(12, 2) DEFAULT 0, -- Amount applied to outstanding balance
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_customer_payments_customer_id ON public.tblcustomer_payments(customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_payments_sales_id ON public.tblcustomer_payments(sales_id);
CREATE INDEX IF NOT EXISTS idx_customer_payments_date ON public.tblcustomer_payments(payment_date);

COMMENT ON TABLE public.tblcustomer_payments IS 'Customer payment history and tracking';


-- =====================================================
-- SECTION 13: STATEMENT OF ACCOUNT (SOA) TABLE
-- Purpose: Generate and store SOA for sub-dealers
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tblstatement_of_account (
  id BIGSERIAL PRIMARY KEY,
  soa_number TEXT GENERATED ALWAYS AS ('SOA-' || LPAD(id::TEXT, 6, '0')) STORED,
  customer_id UUID NOT NULL REFERENCES public.tblcustomer(id) ON UPDATE CASCADE ON DELETE CASCADE,
  period_from DATE NOT NULL,
  period_to DATE NOT NULL,
  opening_balance NUMERIC(12, 2) DEFAULT 0,
  total_charges NUMERIC(12, 2) DEFAULT 0, -- New sales/charges
  total_payments NUMERIC(12, 2) DEFAULT 0,
  closing_balance NUMERIC(12, 2) DEFAULT 0,
  soa_status VARCHAR(20) DEFAULT 'draft' CHECK (soa_status IN ('draft', 'sent', 'paid', 'overdue')),
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  generated_by BIGINT REFERENCES public.tblusers(id),
  sent_at TIMESTAMPTZ,
  due_date DATE,
  notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_soa_customer_id ON public.tblstatement_of_account(customer_id);
CREATE INDEX IF NOT EXISTS idx_soa_status ON public.tblstatement_of_account(soa_status);
CREATE INDEX IF NOT EXISTS idx_soa_period ON public.tblstatement_of_account(period_from, period_to);

COMMENT ON TABLE public.tblstatement_of_account IS 'Statement of Account for sub-dealers';


-- =====================================================
-- SECTION 14: ACCOUNTING - CHEQUE VOUCHER
-- Purpose: Manage cheque vouchers for disbursements
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tblcheque_voucher (
  id BIGSERIAL PRIMARY KEY,
  cv_number TEXT GENERATED ALWAYS AS ('CV-' || LPAD(id::TEXT, 6, '0')) STORED,
  payee_name TEXT NOT NULL,
  payee_address TEXT,
  payee_tin VARCHAR(50),
  cheque_number VARCHAR(50),
  bank_name VARCHAR(100),
  cheque_date DATE,
  amount NUMERIC(12, 2) NOT NULL,
  amount_in_words TEXT,
  particulars TEXT NOT NULL, -- Description of payment
  account_code VARCHAR(50), -- Chart of accounts code
  category VARCHAR(50), -- Expense category
  payment_type VARCHAR(50), -- Supplier Payment, Salary, Utilities, etc.
  status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'issued', 'cleared', 'cancelled')),
  approved_by BIGINT REFERENCES public.tblusers(id),
  approved_at TIMESTAMPTZ,
  issued_by BIGINT REFERENCES public.tblusers(id),
  issued_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id),
  updated_at TIMESTAMPTZ,
  updated_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_cheque_voucher_status ON public.tblcheque_voucher(status);
CREATE INDEX IF NOT EXISTS idx_cheque_voucher_date ON public.tblcheque_voucher(cheque_date);
CREATE INDEX IF NOT EXISTS idx_cheque_voucher_payee ON public.tblcheque_voucher(payee_name);

COMMENT ON TABLE public.tblcheque_voucher IS 'Cheque voucher management for disbursements';


-- =====================================================
-- SECTION 15: ACCOUNTING - GENERAL JOURNAL
-- Purpose: Record all accounting journal entries
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tblgeneral_journal (
  id BIGSERIAL PRIMARY KEY,
  journal_number TEXT GENERATED ALWAYS AS ('JE-' || LPAD(id::TEXT, 6, '0')) STORED,
  journal_date DATE NOT NULL,
  reference_type VARCHAR(50), -- SO, PO, CV, Manual, etc.
  reference_id INTEGER, -- ID of related transaction
  reference_number TEXT,
  description TEXT NOT NULL,
  total_debit NUMERIC(12, 2) DEFAULT 0,
  total_credit NUMERIC(12, 2) DEFAULT 0,
  status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'posted', 'reversed')),
  posted_at TIMESTAMPTZ,
  posted_by BIGINT REFERENCES public.tblusers(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_general_journal_date ON public.tblgeneral_journal(journal_date);
CREATE INDEX IF NOT EXISTS idx_general_journal_status ON public.tblgeneral_journal(status);
CREATE INDEX IF NOT EXISTS idx_general_journal_reference ON public.tblgeneral_journal(reference_type, reference_id);

COMMENT ON TABLE public.tblgeneral_journal IS 'General journal entries for accounting';


-- =====================================================
-- SECTION 16: ACCOUNTING - JOURNAL ENTRY LINES
-- Purpose: Detailed line items for journal entries
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tbljournal_entry_lines (
  id BIGSERIAL PRIMARY KEY,
  journal_id BIGINT NOT NULL REFERENCES public.tblgeneral_journal(id) ON DELETE CASCADE,
  line_number INTEGER NOT NULL,
  account_code VARCHAR(50) NOT NULL,
  account_name TEXT NOT NULL,
  description TEXT,
  debit_amount NUMERIC(12, 2) DEFAULT 0,
  credit_amount NUMERIC(12, 2) DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_journal_lines_journal_id ON public.tbljournal_entry_lines(journal_id);
CREATE INDEX IF NOT EXISTS idx_journal_lines_account ON public.tbljournal_entry_lines(account_code);

COMMENT ON TABLE public.tbljournal_entry_lines IS 'Line items for general journal entries';


-- =====================================================
-- SECTION 17: ACCOUNTING - 2307 TAX REPORT
-- Purpose: Track withholding tax (BIR Form 2307)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tbltax_2307 (
  id BIGSERIAL PRIMARY KEY,
  tax_year INTEGER NOT NULL,
  tax_quarter INTEGER CHECK (tax_quarter BETWEEN 1 AND 4),
  tax_month INTEGER CHECK (tax_month BETWEEN 1 AND 12),
  payee_name TEXT NOT NULL,
  payee_tin VARCHAR(50) NOT NULL,
  payee_address TEXT,
  income_payment_type VARCHAR(100), -- Professional Fees, Rental, etc.
  atc_code VARCHAR(10), -- Alphanumeric Tax Code
  gross_amount NUMERIC(12, 2) NOT NULL,
  tax_rate NUMERIC(5, 2) NOT NULL, -- Percentage
  tax_withheld NUMERIC(12, 2) NOT NULL,
  payment_date DATE,
  reference_type VARCHAR(50), -- CV, SO, PO
  reference_id INTEGER,
  reference_number TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT REFERENCES public.tblusers(id)
);

CREATE INDEX IF NOT EXISTS idx_tax_2307_year_quarter ON public.tbltax_2307(tax_year, tax_quarter);
CREATE INDEX IF NOT EXISTS idx_tax_2307_payee_tin ON public.tbltax_2307(payee_tin);
CREATE INDEX IF NOT EXISTS idx_tax_2307_date ON public.tbltax_2307(payment_date);

COMMENT ON TABLE public.tbltax_2307 IS 'BIR Form 2307 - Certificate of Creditable Tax Withheld at Source';


-- =====================================================
-- SECTION 18: PAYMENT TYPE ENHANCEMENT
-- Purpose: Differentiate sales payments from expenses
-- =====================================================

ALTER TABLE public.tblso_payments 
ADD COLUMN IF NOT EXISTS payment_type VARCHAR(20) DEFAULT 'sales' CHECK (payment_type IN ('sales', 'expense'));

ALTER TABLE public.tblso_payments 
ADD COLUMN IF NOT EXISTS amount NUMERIC(12, 2) DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_so_payments_type ON public.tblso_payments(payment_type);

COMMENT ON COLUMN public.tblso_payments.payment_type IS 'Payment type: sales for customer payments, expense for transfer expenses';


-- =====================================================
-- SECTION 19: RBAC ENHANCEMENT FOR ACCOUNTING
-- Purpose: Add accounting-specific permissions
-- =====================================================

-- Accounting permissions will be managed through existing tblrbac table
-- Sample permission keys for accounting:
-- - accounting.cheque_voucher.canCreate
-- - accounting.cheque_voucher.canRead
-- - accounting.cheque_voucher.canUpdate
-- - accounting.cheque_voucher.canDelete
-- - accounting.general_journal.canCreate
-- - accounting.reports.canView
-- - accounting.tax_2307.canGenerate

COMMENT ON TABLE public.tblrbac IS 'Role-based access control with support for accounting permissions';


-- =====================================================
-- SECTION 20: AUDIT LOG TABLE
-- Purpose: Track all important system changes
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tblaudit_log (
  id BIGSERIAL PRIMARY KEY,
  table_name VARCHAR(100) NOT NULL,
  record_id TEXT NOT NULL,
  action VARCHAR(20) NOT NULL CHECK (action IN ('CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'CANCEL')),
  old_values JSONB,
  new_values JSONB,
  changed_by BIGINT REFERENCES public.tblusers(id),
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ip_address VARCHAR(50),
  user_agent TEXT
);

CREATE INDEX IF NOT EXISTS idx_audit_log_table_record ON public.tblaudit_log(table_name, record_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_changed_by ON public.tblaudit_log(changed_by);
CREATE INDEX IF NOT EXISTS idx_audit_log_changed_at ON public.tblaudit_log(changed_at);

COMMENT ON TABLE public.tblaudit_log IS 'System-wide audit trail for tracking changes';


-- =====================================================
-- SECTION 21: HELPER FUNCTIONS
-- Purpose: Utility functions for common operations
-- =====================================================

-- Function to update material stock after purchase order approval
CREATE OR REPLACE FUNCTION update_material_stock_on_po_approval()
RETURNS TRIGGER AS $$
BEGIN
  -- Only update stock when status changes to APPROVED
  IF NEW.status = 'APPROVED' AND OLD.status != 'APPROVED' AND NEW.po_type = 'MATERIAL' THEN
    -- Update material stock from transaction items
    UPDATE public.tblmaterials m
    SET on_hand_stock = on_hand_stock + tmi.quantity,
        updated_at = NOW()
    FROM public.tbltransaction_material_items tmi
    WHERE tmi.purchase_id = NEW.id 
      AND tmi.material_id = m.id
      AND tmi.trans_type = 'purchase';
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for material stock update
DROP TRIGGER IF EXISTS trg_update_material_stock_on_po_approval ON public.tblpurchase_orders;
CREATE TRIGGER trg_update_material_stock_on_po_approval
  AFTER UPDATE ON public.tblpurchase_orders
  FOR EACH ROW
  EXECUTE FUNCTION update_material_stock_on_po_approval();

COMMENT ON FUNCTION update_material_stock_on_po_approval() IS 'Automatically update material stock when PO is approved';


-- Helper: Recalculate a customer balance based on sales orders and payments
CREATE OR REPLACE FUNCTION recalc_customer_balance(p_customer_id UUID)
RETURNS VOID AS $$
BEGIN
  UPDATE public.tblcustomer
  SET current_balance = (
    -- total sales for the customer
    COALESCE(
      (SELECT SUM(total_amount) FROM public.tblsales_order WHERE customer_id = p_customer_id),
      0
    )
    -- subtract customer payments (legacy table)
    - COALESCE(
      (SELECT SUM(payment_amount) FROM public.tblcustomer_payments WHERE customer_id = p_customer_id),
      0
    )
    -- subtract sales order payments (current table, only paid ones)
    - COALESCE(
      (
        SELECT SUM(COALESCE(sp.amount, 0))
        FROM public.tblso_payments sp
        JOIN public.tblsales_order so ON so.id = sp.so_id
        WHERE so.customer_id = p_customer_id
          AND LOWER(COALESCE(sp.status, 'paid')) = 'paid'
          AND LOWER(COALESCE(sp.payment_type, 'sales')) = 'sales'
      ),
      0
    )
  ),
  updated_at = NOW()
  WHERE id = p_customer_id;
END;
$$ LANGUAGE plpgsql;

-- Trigger: Update balance when a sales order changes
CREATE OR REPLACE FUNCTION update_customer_balance_on_sales()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.customer_id IS NOT NULL THEN
    PERFORM recalc_customer_balance(NEW.customer_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_customer_balance_on_sales ON public.tblsales_order;
CREATE TRIGGER trg_update_customer_balance_on_sales
  AFTER INSERT OR UPDATE ON public.tblsales_order
  FOR EACH ROW
  EXECUTE FUNCTION update_customer_balance_on_sales();

-- Trigger: Update balance when a customer payment record changes (legacy table)
CREATE OR REPLACE FUNCTION update_customer_balance_on_customer_payment()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.customer_id IS NOT NULL THEN
    PERFORM recalc_customer_balance(NEW.customer_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_customer_balance_on_payment ON public.tblcustomer_payments;
CREATE TRIGGER trg_update_customer_balance_on_payment
  AFTER INSERT OR UPDATE ON public.tblcustomer_payments
  FOR EACH ROW
  EXECUTE FUNCTION update_customer_balance_on_customer_payment();

-- Trigger: Update balance when a sales order payment is recorded/updated
CREATE OR REPLACE FUNCTION update_customer_balance_on_so_payment()
RETURNS TRIGGER AS $$
DECLARE
  v_customer_id UUID;
BEGIN
  -- Find customer for the associated sales order
  SELECT customer_id INTO v_customer_id FROM public.tblsales_order WHERE id = NEW.so_id;
  IF v_customer_id IS NOT NULL THEN
    PERFORM recalc_customer_balance(v_customer_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_customer_balance_on_so_payment ON public.tblso_payments;
CREATE TRIGGER trg_update_customer_balance_on_so_payment
  AFTER INSERT OR UPDATE ON public.tblso_payments
  FOR EACH ROW
  EXECUTE FUNCTION update_customer_balance_on_so_payment();

COMMENT ON FUNCTION recalc_customer_balance(UUID) IS 'Recalculates a customer''s current balance based on sales orders and paid payments';
COMMENT ON FUNCTION update_customer_balance_on_sales() IS 'Trigger: recalc balance when a sales order changes';
COMMENT ON FUNCTION update_customer_balance_on_customer_payment() IS 'Trigger: recalc balance when a customer payment record changes (legacy)';
COMMENT ON FUNCTION update_customer_balance_on_so_payment() IS 'Trigger: recalc balance when a sales order payment record changes';


-- =====================================================
-- SECTION 22: SAMPLE DATA INSERTS (Optional)
-- Purpose: Insert sample data for testing
-- =====================================================

-- Insert sample material brands (commented out - uncomment if needed)
-- INSERT INTO public.tblbrands (brandName, prefix, type) VALUES
-- ('Generic Materials', 'GEN', 'MAT'),
-- ('Premium Pipes Co.', 'PPC', 'MAT'),
-- ('ElectroWire Inc.', 'EWI', 'MAT')
-- ON CONFLICT DO NOTHING;


-- =====================================================
-- MIGRATION COMPLETE
-- =====================================================

-- Verify migration
DO $$
BEGIN
  RAISE NOTICE 'Migration 20260310_material_inventory_enhancement completed successfully!';
  RAISE NOTICE 'Tables created: tblmaterials, tblproject_details, tblservice_details, tblconcern_details, tbltransfer_details, tblexpense_details, tblcustomer_payments, tblstatement_of_account, tblcheque_voucher, tblgeneral_journal, tbljournal_entry_lines, tbltax_2307, tblaudit_log';
  RAISE NOTICE 'Enhancements: Brand types, PO types, Customer types, Payment types';
  RAISE NOTICE 'Triggers: Material stock update, Customer balance update';
END $$;

-- END FILE: 20260310_material_inventory_enhancement.sql


-- ============================================================
-- BEGIN FILE: 20260312_sales_order_project_fields.sql
-- ============================================================

-- Add project-related fields to sales orders so we can capture additional metadata when salesType = 'project'.

ALTER TABLE public.tblsales_order
  ADD COLUMN IF NOT EXISTS project_name text NULL,
  ADD COLUMN IF NOT EXISTS project_code text NULL;

-- END FILE: 20260312_sales_order_project_fields.sql


-- ============================================================
-- BEGIN FILE: 20260313_serial_defect_return_fields.sql
-- ============================================================

-- Add new fields to tblserial_numbers for defect and return tracking
ALTER TABLE public.tblserial_numbers
ADD COLUMN IF NOT EXISTS "isDefective" boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS "isReturned" boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS "defectReason" text,
ADD COLUMN IF NOT EXISTS "returnReason" text,
ADD COLUMN IF NOT EXISTS "defectDate" timestamp with time zone,
ADD COLUMN IF NOT EXISTS "returnDate" timestamp with time zone;

-- Add comments for documentation
COMMENT ON COLUMN public.tblserial_numbers."isDefective" IS 'Flag indicating if the serial number is defective';
COMMENT ON COLUMN public.tblserial_numbers."isReturned" IS 'Flag indicating if the serial number has been returned';
COMMENT ON COLUMN public.tblserial_numbers."defectReason" IS 'Reason for defect if isDefective is true';
COMMENT ON COLUMN public.tblserial_numbers."returnReason" IS 'Reason for return if isReturned is true';
COMMENT ON COLUMN public.tblserial_numbers."defectDate" IS 'Date when defect was recorded';
COMMENT ON COLUMN public.tblserial_numbers."returnDate" IS 'Date when return was recorded';

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_tblserial_numbers_isDefective ON public.tblserial_numbers("isDefective") WHERE "isDefective" = true;
CREATE INDEX IF NOT EXISTS idx_tblserial_numbers_isReturned ON public.tblserial_numbers("isReturned") WHERE "isReturned" = true;

-- END FILE: 20260313_serial_defect_return_fields.sql


-- ============================================================
-- BEGIN FILE: 20260317_po_payment_bank_cheque_fields.sql
-- ============================================================

ALTER TABLE IF EXISTS tblpo_payments
  ADD COLUMN IF NOT EXISTS bank_name TEXT,
  ADD COLUMN IF NOT EXISTS reference_no TEXT,
  ADD COLUMN IF NOT EXISTS check_no TEXT,
  ADD COLUMN IF NOT EXISTS cheque_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS issued_by TEXT;

-- END FILE: 20260317_po_payment_bank_cheque_fields.sql


-- ============================================================
-- BEGIN FILE: 20260318_backfill_branchid.sql
-- ============================================================

-- Migration: Backfill branchId for legacy records
-- Purpose: Assign all existing purchase orders and sales orders without branchId to the default branch
-- 
-- IMPORTANT: Replace '1' with your actual default branch ID before running
-- Run this query to see available branches:
-- SELECT id, "branchName" FROM public.tblbranches ORDER BY id;

-- Step 1: Check how many records need backfilling BEFORE update
SELECT 'BEFORE UPDATE - Purchase Orders' as status, COUNT(*) as records_without_branchid
FROM public.tblpurchase_orders 
WHERE "branchId" IS NULL
UNION ALL
SELECT 'BEFORE UPDATE - Sales Orders' as status, COUNT(*) as records_without_branchid
FROM public.tblsales_order 
WHERE "branchId" IS NULL;

-- Step 2: Backfill Purchase Orders (change '1' to your default branch ID)
UPDATE public.tblpurchase_orders 
SET "branchId" = 1
WHERE "branchId" IS NULL;

-- Step 3: Backfill Sales Orders (change '1' to your default branch ID)
UPDATE public.tblsales_order 
SET "branchId" = 1
WHERE "branchId" IS NULL;

-- Step 4: Verify the updates AFTER update
SELECT 'AFTER UPDATE - Purchase Orders' as status, COUNT(*) as records_without_branchid
FROM public.tblpurchase_orders 
WHERE "branchId" IS NULL
UNION ALL
SELECT 'AFTER UPDATE - Sales Orders' as status, COUNT(*) as records_without_branchid
FROM public.tblsales_order 
WHERE "branchId" IS NULL;

-- Step 5: Show final record counts with branchId
SELECT 'Purchase Orders' as record_type, COUNT(*) as total, 
       SUM(CASE WHEN "branchId" IS NULL THEN 1 ELSE 0 END) as null_count,
       SUM(CASE WHEN "branchId" IS NOT NULL THEN 1 ELSE 0 END) as with_branchid
FROM public.tblpurchase_orders
UNION ALL
SELECT 'Sales Orders' as record_type, COUNT(*) as total,
       SUM(CASE WHEN "branchId" IS NULL THEN 1 ELSE 0 END) as null_count,
       SUM(CASE WHEN "branchId" IS NOT NULL THEN 1 ELSE 0 END) as with_branchid
FROM public.tblsales_order;

-- END FILE: 20260318_backfill_branchid.sql


-- ============================================================
-- BEGIN FILE: 20260318_quotation_terms_conditions.sql
-- ============================================================

-- Migration: Add terms_conditions JSONB column to tblquotation
-- Date: 2026-03-18
-- Purpose: Store editable T&C fields per quotation (Warranty Exception, Validity, Note, Penalty Fee, Warranty)

ALTER TABLE public.tblquotation
  ADD COLUMN IF NOT EXISTS terms_conditions JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMENT ON COLUMN public.tblquotation.terms_conditions IS
  'Stores editable Terms & Conditions fields per quotation: warrantyException, validity, note, penaltyFee, warranty';

-- END FILE: 20260318_quotation_terms_conditions.sql


-- ============================================================
-- BEGIN FILE: 20260318_settings_report_assets.sql
-- ============================================================

ALTER TABLE public.tblsettings
  ADD COLUMN IF NOT EXISTS "businessLogoLight" TEXT,
  ADD COLUMN IF NOT EXISTS "businessLogoDark" TEXT,
  ADD COLUMN IF NOT EXISTS "drTemplatePdf" TEXT;

-- END FILE: 20260318_settings_report_assets.sql


-- ============================================================
-- BEGIN FILE: 20260320_quotation_expiry.sql
-- ============================================================

-- Migration: add quotation validity and expiry lifecycle fields

ALTER TABLE public.tblquotation
  ADD COLUMN IF NOT EXISTS validity_days integer NOT NULL DEFAULT 14,
  ADD COLUMN IF NOT EXISTS expires_at timestamptz NULL,
  ADD COLUMN IF NOT EXISTS expired_at timestamptz NULL,
  ADD COLUMN IF NOT EXISTS is_deleted boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz NULL;

ALTER TABLE public.tblquotation
  DROP CONSTRAINT IF EXISTS tblquotation_status_check;

ALTER TABLE public.tblquotation
  ADD CONSTRAINT tblquotation_status_check
  CHECK (LOWER(status) IN ('draft', 'finalized', 'converted', 'cancelled', 'expired'));

UPDATE public.tblquotation
SET
  validity_days = COALESCE(validity_days, 14),
  expires_at = COALESCE(
    expires_at,
    COALESCE(quote_date, created_at, NOW())
      + make_interval(days => GREATEST(COALESCE(validity_days, 14), 1))
  )
WHERE expires_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_tblquotation_is_deleted
  ON public.tblquotation(is_deleted);

CREATE INDEX IF NOT EXISTS idx_tblquotation_expires_at
  ON public.tblquotation(expires_at);

COMMENT ON COLUMN public.tblquotation.validity_days IS
  'Quotation validity in days used to auto-expire draft quotations.';

COMMENT ON COLUMN public.tblquotation.expires_at IS
  'Timestamp when the quotation becomes expired based on quote_date + validity_days.';

COMMENT ON COLUMN public.tblquotation.expired_at IS
  'Timestamp when the quotation was marked expired and moved to trash.';

COMMENT ON COLUMN public.tblquotation.is_deleted IS
  'Soft-delete flag used for expired quotations moved to trash.';

COMMENT ON COLUMN public.tblquotation.deleted_at IS
  'Timestamp when a quotation was soft-deleted into trash.';

-- END FILE: 20260320_quotation_expiry.sql


-- ============================================================
-- BEGIN FILE: 20260322_business_owner_accounting_rbac.sql
-- ============================================================

-- Business Owner role + RBAC expansion (Accounting + Inventory Land Costing)
-- Date: 2026-03-22

BEGIN;

-- 1) Ensure permission keys exist for Accounting, Inventory Land Costing, and latest PO actions/tabs.
INSERT INTO public.auth_permission_keys(key, label, module, scope)
VALUES
  ('accounting.view', 'View Accounting Module', 'accounting', 'feature'),
  ('accounting.report.cheque-voucher.view', 'Accounting Report: Cheque Voucher', 'accounting', 'feature'),
  ('accounting.report.general-journal-register.view', 'Accounting Report: General Journal Register', 'accounting', 'feature'),
  ('accounting.report.disbursement-register.view', 'Accounting Report: Disbursement Register', 'accounting', 'feature'),
  ('accounting.report.sales-register.view', 'Accounting Report: Sales Register', 'accounting', 'feature'),
  ('accounting.report.tax-2307-report.view', 'Accounting Report: 2307 Tax Report', 'accounting', 'feature'),
  ('accounting.report.weekly-sales.view', 'Accounting Report: Weekly Sales', 'accounting', 'feature'),
  ('accounting.report.daily-unit-released.view', 'Accounting Report: Daily Unit Released', 'accounting', 'feature'),
  ('accounting.report.low-stocks-report.view', 'Accounting Report: Low Stocks', 'accounting', 'feature'),

  ('accounting.report.action.generate', 'Accounting Action: Generate Report', 'accounting', 'action'),
  ('accounting.report.action.export', 'Accounting Action: Export Report', 'accounting', 'action'),
  ('accounting.report.action.print', 'Accounting Action: Print Report', 'accounting', 'action'),
  ('accounting.report.action.edit-draft', 'Accounting Action: Edit Draft Workflows', 'accounting', 'action'),

  ('inventory.land-costing.view', 'Inventory: View Land Costing Report', 'inventory', 'feature'),
  ('inventory.land-costing.margin.view', 'Inventory: View Land Costing Margin', 'inventory', 'feature'),
  ('inventory.land-costing.export', 'Inventory: Export Land Costing Report', 'inventory', 'action'),

  ('purchase-order.tab.deliveries', 'PO Tab: Deliveries', 'purchase-order', 'tab'),
  ('purchase-order.tab.approvals', 'PO Tab: Approvals', 'purchase-order', 'tab'),
  ('purchase-order.tab.master-data', 'PO Tab: Master Data', 'purchase-order', 'tab'),
  ('purchase-order.button.send-for-approval', 'PO Action: Send for Approval', 'purchase-order', 'action'),
  ('purchase-order.button.revert-deliveries', 'PO Action: Revert to Deliveries', 'purchase-order', 'action')
ON CONFLICT (key) DO NOTHING;

-- 2) Create Business Owner role in tblrbac (idempotent), copying legacy menu/permission CSVs from existing admin/super role when possible.
DO $$
DECLARE
  role_name_col TEXT;
  role_menus_col TEXT;
  role_permission_col TEXT;
  source_role_id BIGINT;
  existing_business_owner_id BIGINT;
BEGIN
  SELECT c.column_name
  INTO role_name_col
  FROM information_schema.columns c
  WHERE c.table_schema = 'public' AND c.table_name = 'tblrbac' AND lower(c.column_name) = 'rolename'
  LIMIT 1;

  SELECT c.column_name
  INTO role_menus_col
  FROM information_schema.columns c
  WHERE c.table_schema = 'public' AND c.table_name = 'tblrbac' AND lower(c.column_name) = 'rolemenus'
  LIMIT 1;

  SELECT c.column_name
  INTO role_permission_col
  FROM information_schema.columns c
  WHERE c.table_schema = 'public' AND c.table_name = 'tblrbac' AND lower(c.column_name) = 'rolepermission'
  LIMIT 1;

  IF role_name_col IS NULL THEN
    RAISE EXCEPTION 'tblrbac role name column not found (expected roleName/rolename).';
  END IF;

  EXECUTE format(
    'SELECT id FROM public.tblrbac WHERE lower(coalesce(%I::text, '''')) = lower(''Business Owner'') LIMIT 1',
    role_name_col
  ) INTO existing_business_owner_id;

  IF existing_business_owner_id IS NOT NULL THEN
    RETURN;
  END IF;

  EXECUTE format(
    'SELECT id
       FROM public.tblrbac
      WHERE lower(coalesce(%I::text, '''')) LIKE ''%%admin%%''
         OR lower(coalesce(%I::text, '''')) LIKE ''%%super%%''
      ORDER BY id
      LIMIT 1',
    role_name_col,
    role_name_col
  ) INTO source_role_id;

  IF role_menus_col IS NOT NULL AND role_permission_col IS NOT NULL AND source_role_id IS NOT NULL THEN
    EXECUTE format(
      'INSERT INTO public.tblrbac (%I, %I, %I)
       SELECT ''Business Owner'', coalesce(src.%I::text, ''''), coalesce(src.%I::text, '''')
       FROM public.tblrbac src
       WHERE src.id = $1',
      role_name_col,
      role_menus_col,
      role_permission_col,
      role_menus_col,
      role_permission_col
    ) USING source_role_id;
  ELSIF role_menus_col IS NOT NULL AND role_permission_col IS NOT NULL THEN
    EXECUTE format(
      'INSERT INTO public.tblrbac (%I, %I, %I)
       VALUES (''Business Owner'', '''', '''')',
      role_name_col,
      role_menus_col,
      role_permission_col
    );
  ELSE
    EXECUTE format(
      'INSERT INTO public.tblrbac (%I)
       VALUES (''Business Owner'')',
      role_name_col
    );
  END IF;
END
$$;

-- 3) Business Owner acts as superadmin: assign ALL auth permission keys to the role.
WITH business_owner_role AS (
  SELECT id AS role_id
  FROM public.tblrbac r
  WHERE lower(coalesce(to_jsonb(r)->>'roleName', to_jsonb(r)->>'rolename', '')) = 'business owner'
  LIMIT 1
)
INSERT INTO public.auth_role_permissions(role_id, permission_id)
SELECT bo.role_id, pk.id
FROM business_owner_role bo
CROSS JOIN public.auth_permission_keys pk
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- 4) Ensure existing admin/super roles receive NEW keys introduced by this migration.
WITH privileged_roles AS (
  SELECT r.id AS role_id
  FROM public.tblrbac r
  WHERE lower(coalesce(to_jsonb(r)->>'roleName', to_jsonb(r)->>'rolename', '')) LIKE '%admin%'
     OR lower(coalesce(to_jsonb(r)->>'roleName', to_jsonb(r)->>'rolename', '')) LIKE '%super%'
), new_keys AS (
  SELECT id
  FROM public.auth_permission_keys
  WHERE key IN (
    'accounting.view',
    'accounting.report.cheque-voucher.view',
    'accounting.report.general-journal-register.view',
    'accounting.report.disbursement-register.view',
    'accounting.report.sales-register.view',
    'accounting.report.tax-2307-report.view',
    'accounting.report.weekly-sales.view',
    'accounting.report.daily-unit-released.view',
    'accounting.report.low-stocks-report.view',
    'accounting.report.action.generate',
    'accounting.report.action.export',
    'accounting.report.action.print',
    'accounting.report.action.edit-draft',
    'inventory.land-costing.view',
    'inventory.land-costing.margin.view',
    'inventory.land-costing.export',
    'purchase-order.tab.deliveries',
    'purchase-order.tab.approvals',
    'purchase-order.tab.master-data',
    'purchase-order.button.send-for-approval',
    'purchase-order.button.revert-deliveries'
  )
)
INSERT INTO public.auth_role_permissions(role_id, permission_id)
SELECT pr.role_id, nk.id
FROM privileged_roles pr
CROSS JOIN new_keys nk
ON CONFLICT (role_id, permission_id) DO NOTHING;

COMMIT;

-- END FILE: 20260322_business_owner_accounting_rbac.sql

